// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddBreachHandler(ReducerEventContext ctx, float delta);
        public event AddBreachHandler? OnAddBreach;

        public void AddBreach(float delta)
        {
            conn.InternalCallReducer(new Reducer.AddBreach(delta));
        }

        public bool InvokeAddBreach(ReducerEventContext ctx, Reducer.AddBreach args)
        {
            if (OnAddBreach == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddBreach(
                ctx,
                args.Delta
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddBreach : Reducer, IReducerArgs
        {
            [DataMember(Name = "delta")]
            public float Delta;

            public AddBreach(float Delta)
            {
                this.Delta = Delta;
            }

            public AddBreach()
            {
            }

            string IReducerArgs.ReducerName => "add_breach";
        }
    }
}
