// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyRelationshipHandler(ReducerEventContext ctx, ulong npcId, SpacetimeDB.Identity player, float trustDelta, float fearDelta, string addFlag, string memoryNote);
        public event ApplyRelationshipHandler? OnApplyRelationship;

        public void ApplyRelationship(ulong npcId, SpacetimeDB.Identity player, float trustDelta, float fearDelta, string addFlag, string memoryNote)
        {
            conn.InternalCallReducer(new Reducer.ApplyRelationship(npcId, player, trustDelta, fearDelta, addFlag, memoryNote));
        }

        public bool InvokeApplyRelationship(ReducerEventContext ctx, Reducer.ApplyRelationship args)
        {
            if (OnApplyRelationship == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnApplyRelationship(
                ctx,
                args.NpcId,
                args.Player,
                args.TrustDelta,
                args.FearDelta,
                args.AddFlag,
                args.MemoryNote
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyRelationship : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "player")]
            public SpacetimeDB.Identity Player;
            [DataMember(Name = "trust_delta")]
            public float TrustDelta;
            [DataMember(Name = "fear_delta")]
            public float FearDelta;
            [DataMember(Name = "add_flag")]
            public string AddFlag;
            [DataMember(Name = "memory_note")]
            public string MemoryNote;

            public ApplyRelationship(
                ulong NpcId,
                SpacetimeDB.Identity Player,
                float TrustDelta,
                float FearDelta,
                string AddFlag,
                string MemoryNote
            )
            {
                this.NpcId = NpcId;
                this.Player = Player;
                this.TrustDelta = TrustDelta;
                this.FearDelta = FearDelta;
                this.AddFlag = AddFlag;
                this.MemoryNote = MemoryNote;
            }

            public ApplyRelationship()
            {
                this.AddFlag = "";
                this.MemoryNote = "";
            }

            string IReducerArgs.ReducerName => "apply_relationship";
        }
    }
}
