// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AskNpcHandler(ReducerEventContext ctx, ulong npcId, string transcript, float playerDistance, bool isPlayerArmed, bool flashlightInFace);
        public event AskNpcHandler? OnAskNpc;

        public void AskNpc(ulong npcId, string transcript, float playerDistance, bool isPlayerArmed, bool flashlightInFace)
        {
            conn.InternalCallReducer(new Reducer.AskNpc(npcId, transcript, playerDistance, isPlayerArmed, flashlightInFace));
        }

        public bool InvokeAskNpc(ReducerEventContext ctx, Reducer.AskNpc args)
        {
            if (OnAskNpc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAskNpc(
                ctx,
                args.NpcId,
                args.Transcript,
                args.PlayerDistance,
                args.IsPlayerArmed,
                args.FlashlightInFace
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AskNpc : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "transcript")]
            public string Transcript;
            [DataMember(Name = "player_distance")]
            public float PlayerDistance;
            [DataMember(Name = "is_player_armed")]
            public bool IsPlayerArmed;
            [DataMember(Name = "flashlight_in_face")]
            public bool FlashlightInFace;

            public AskNpc(
                ulong NpcId,
                string Transcript,
                float PlayerDistance,
                bool IsPlayerArmed,
                bool FlashlightInFace
            )
            {
                this.NpcId = NpcId;
                this.Transcript = Transcript;
                this.PlayerDistance = PlayerDistance;
                this.IsPlayerArmed = IsPlayerArmed;
                this.FlashlightInFace = FlashlightInFace;
            }

            public AskNpc()
            {
                this.Transcript = "";
            }

            string IReducerArgs.ReducerName => "ask_npc";
        }
    }
}
