// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimBillionaireRequestHandler(ReducerEventContext ctx, ulong requestId);
        public event ClaimBillionaireRequestHandler? OnClaimBillionaireRequest;

        public void ClaimBillionaireRequest(ulong requestId)
        {
            conn.InternalCallReducer(new Reducer.ClaimBillionaireRequest(requestId));
        }

        public bool InvokeClaimBillionaireRequest(ReducerEventContext ctx, Reducer.ClaimBillionaireRequest args)
        {
            if (OnClaimBillionaireRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimBillionaireRequest(
                ctx,
                args.RequestId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimBillionaireRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;

            public ClaimBillionaireRequest(ulong RequestId)
            {
                this.RequestId = RequestId;
            }

            public ClaimBillionaireRequest()
            {
            }

            string IReducerArgs.ReducerName => "claim_billionaire_request";
        }
    }
}
