// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FailBillionaireRequestHandler(ReducerEventContext ctx, ulong requestId, string reason);
        public event FailBillionaireRequestHandler? OnFailBillionaireRequest;

        public void FailBillionaireRequest(ulong requestId, string reason)
        {
            conn.InternalCallReducer(new Reducer.FailBillionaireRequest(requestId, reason));
        }

        public bool InvokeFailBillionaireRequest(ReducerEventContext ctx, Reducer.FailBillionaireRequest args)
        {
            if (OnFailBillionaireRequest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFailBillionaireRequest(
                ctx,
                args.RequestId,
                args.Reason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FailBillionaireRequest : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;
            [DataMember(Name = "reason")]
            public string Reason;

            public FailBillionaireRequest(
                ulong RequestId,
                string Reason
            )
            {
                this.RequestId = RequestId;
                this.Reason = Reason;
            }

            public FailBillionaireRequest()
            {
                this.Reason = "";
            }

            string IReducerArgs.ReducerName => "fail_billionaire_request";
        }
    }
}
