// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void NpcRespondHandler(ReducerEventContext ctx, ulong npcId, ulong interactionId, string dialogue, string animationTrigger, string gameAction, SpacetimeDB.Identity? targetPlayer, int trustChange, int sanityChange);
        public event NpcRespondHandler? OnNpcRespond;

        public void NpcRespond(ulong npcId, ulong interactionId, string dialogue, string animationTrigger, string gameAction, SpacetimeDB.Identity? targetPlayer, int trustChange, int sanityChange)
        {
            conn.InternalCallReducer(new Reducer.NpcRespond(npcId, interactionId, dialogue, animationTrigger, gameAction, targetPlayer, trustChange, sanityChange));
        }

        public bool InvokeNpcRespond(ReducerEventContext ctx, Reducer.NpcRespond args)
        {
            if (OnNpcRespond == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnNpcRespond(
                ctx,
                args.NpcId,
                args.InteractionId,
                args.Dialogue,
                args.AnimationTrigger,
                args.GameAction,
                args.TargetPlayer,
                args.TrustChange,
                args.SanityChange
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class NpcRespond : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "interaction_id")]
            public ulong InteractionId;
            [DataMember(Name = "dialogue")]
            public string Dialogue;
            [DataMember(Name = "animation_trigger")]
            public string AnimationTrigger;
            [DataMember(Name = "game_action")]
            public string GameAction;
            [DataMember(Name = "target_player")]
            public SpacetimeDB.Identity? TargetPlayer;
            [DataMember(Name = "trust_change")]
            public int TrustChange;
            [DataMember(Name = "sanity_change")]
            public int SanityChange;

            public NpcRespond(
                ulong NpcId,
                ulong InteractionId,
                string Dialogue,
                string AnimationTrigger,
                string GameAction,
                SpacetimeDB.Identity? TargetPlayer,
                int TrustChange,
                int SanityChange
            )
            {
                this.NpcId = NpcId;
                this.InteractionId = InteractionId;
                this.Dialogue = Dialogue;
                this.AnimationTrigger = AnimationTrigger;
                this.GameAction = GameAction;
                this.TargetPlayer = TargetPlayer;
                this.TrustChange = TrustChange;
                this.SanityChange = SanityChange;
            }

            public NpcRespond()
            {
                this.Dialogue = "";
                this.AnimationTrigger = "";
                this.GameAction = "";
            }

            string IReducerArgs.ReducerName => "npc_respond";
        }
    }
}
