// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RenewClaimHandler(ReducerEventContext ctx, ulong interactionId);
        public event RenewClaimHandler? OnRenewClaim;

        public void RenewClaim(ulong interactionId)
        {
            conn.InternalCallReducer(new Reducer.RenewClaim(interactionId));
        }

        public bool InvokeRenewClaim(ReducerEventContext ctx, Reducer.RenewClaim args)
        {
            if (OnRenewClaim == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRenewClaim(
                ctx,
                args.InteractionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RenewClaim : Reducer, IReducerArgs
        {
            [DataMember(Name = "interaction_id")]
            public ulong InteractionId;

            public RenewClaim(ulong InteractionId)
            {
                this.InteractionId = InteractionId;
            }

            public RenewClaim()
            {
            }

            string IReducerArgs.ReducerName => "renew_claim";
        }
    }
}
