// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RenewBillionaireClaimHandler(ReducerEventContext ctx, ulong requestId);
        public event RenewBillionaireClaimHandler? OnRenewBillionaireClaim;

        public void RenewBillionaireClaim(ulong requestId)
        {
            conn.InternalCallReducer(new Reducer.RenewBillionaireClaim(requestId));
        }

        public bool InvokeRenewBillionaireClaim(ReducerEventContext ctx, Reducer.RenewBillionaireClaim args)
        {
            if (OnRenewBillionaireClaim == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRenewBillionaireClaim(
                ctx,
                args.RequestId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RenewBillionaireClaim : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;

            public RenewBillionaireClaim(ulong RequestId)
            {
                this.RequestId = RequestId;
            }

            public RenewBillionaireClaim()
            {
            }

            string IReducerArgs.ReducerName => "renew_billionaire_claim";
        }
    }
}
