// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestBillionaireDialogueHandler(ReducerEventContext ctx, string kind, string context, SpacetimeDB.Identity? targetIdentity);
        public event RequestBillionaireDialogueHandler? OnRequestBillionaireDialogue;

        public void RequestBillionaireDialogue(string kind, string context, SpacetimeDB.Identity? targetIdentity)
        {
            conn.InternalCallReducer(new Reducer.RequestBillionaireDialogue(kind, context, targetIdentity));
        }

        public bool InvokeRequestBillionaireDialogue(ReducerEventContext ctx, Reducer.RequestBillionaireDialogue args)
        {
            if (OnRequestBillionaireDialogue == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestBillionaireDialogue(
                ctx,
                args.Kind,
                args.Context,
                args.TargetIdentity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestBillionaireDialogue : Reducer, IReducerArgs
        {
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "context")]
            public string Context;
            [DataMember(Name = "target_identity")]
            public SpacetimeDB.Identity? TargetIdentity;

            public RequestBillionaireDialogue(
                string Kind,
                string Context,
                SpacetimeDB.Identity? TargetIdentity
            )
            {
                this.Kind = Kind;
                this.Context = Context;
                this.TargetIdentity = TargetIdentity;
            }

            public RequestBillionaireDialogue()
            {
                this.Kind = "";
                this.Context = "";
            }

            string IReducerArgs.ReducerName => "request_billionaire_dialogue";
        }
    }
}
