// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RevealClueHandler(ReducerEventContext ctx, ulong npcId, ulong clueId, SpacetimeDB.Identity player);
        public event RevealClueHandler? OnRevealClue;

        public void RevealClue(ulong npcId, ulong clueId, SpacetimeDB.Identity player)
        {
            conn.InternalCallReducer(new Reducer.RevealClue(npcId, clueId, player));
        }

        public bool InvokeRevealClue(ReducerEventContext ctx, Reducer.RevealClue args)
        {
            if (OnRevealClue == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRevealClue(
                ctx,
                args.NpcId,
                args.ClueId,
                args.Player
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RevealClue : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "clue_id")]
            public ulong ClueId;
            [DataMember(Name = "player")]
            public SpacetimeDB.Identity Player;

            public RevealClue(
                ulong NpcId,
                ulong ClueId,
                SpacetimeDB.Identity Player
            )
            {
                this.NpcId = NpcId;
                this.ClueId = ClueId;
                this.Player = Player;
            }

            public RevealClue()
            {
            }

            string IReducerArgs.ReducerName => "reveal_clue";
        }
    }
}
