// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RunCombineReducerHandler(ReducerEventContext ctx, ulong runId);
        public event RunCombineReducerHandler? OnRunCombineReducer;

        public void RunCombineReducer(ulong runId)
        {
            conn.InternalCallReducer(new Reducer.RunCombineReducer(runId));
        }

        public bool InvokeRunCombineReducer(ReducerEventContext ctx, Reducer.RunCombineReducer args)
        {
            if (OnRunCombineReducer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRunCombineReducer(
                ctx,
                args.RunId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RunCombineReducer : Reducer, IReducerArgs
        {
            [DataMember(Name = "run_id")]
            public ulong RunId;

            public RunCombineReducer(ulong RunId)
            {
                this.RunId = RunId;
            }

            public RunCombineReducer()
            {
            }

            string IReducerArgs.ReducerName => "run_combine_reducer";
        }
    }
}
