// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SeedNpcsHandler(ReducerEventContext ctx);
        public event SeedNpcsHandler? OnSeedNpcs;

        public void SeedNpcs()
        {
            conn.InternalCallReducer(new Reducer.SeedNpcs());
        }

        public bool InvokeSeedNpcs(ReducerEventContext ctx, Reducer.SeedNpcs args)
        {
            if (OnSeedNpcs == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSeedNpcs(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SeedNpcs : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "seed_npcs";
        }
    }
}
