// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateNpcMemoryHandler(ReducerEventContext ctx, ulong npcId, string memory);
        public event UpdateNpcMemoryHandler? OnUpdateNpcMemory;

        public void UpdateNpcMemory(ulong npcId, string memory)
        {
            conn.InternalCallReducer(new Reducer.UpdateNpcMemory(npcId, memory));
        }

        public bool InvokeUpdateNpcMemory(ReducerEventContext ctx, Reducer.UpdateNpcMemory args)
        {
            if (OnUpdateNpcMemory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateNpcMemory(
                ctx,
                args.NpcId,
                args.Memory
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateNpcMemory : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public ulong NpcId;
            [DataMember(Name = "memory")]
            public string Memory;

            public UpdateNpcMemory(
                ulong NpcId,
                string Memory
            )
            {
                this.NpcId = NpcId;
                this.Memory = Memory;
            }

            public UpdateNpcMemory()
            {
                this.Memory = "";
            }

            string IReducerArgs.ReducerName => "update_npc_memory";
        }
    }
}
