// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerInputHandler(ReducerEventContext ctx, SpacetimeDB.Types.InputState input, SpacetimeDB.Types.Vector3 clientPos, SpacetimeDB.Types.Vector3 clientRot, string clientAnimation);
        public event UpdatePlayerInputHandler? OnUpdatePlayerInput;

        public void UpdatePlayerInput(SpacetimeDB.Types.InputState input, SpacetimeDB.Types.Vector3 clientPos, SpacetimeDB.Types.Vector3 clientRot, string clientAnimation)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerInput(input, clientPos, clientRot, clientAnimation));
        }

        public bool InvokeUpdatePlayerInput(ReducerEventContext ctx, Reducer.UpdatePlayerInput args)
        {
            if (OnUpdatePlayerInput == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePlayerInput(
                ctx,
                args.Input,
                args.ClientPos,
                args.ClientRot,
                args.ClientAnimation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerInput : Reducer, IReducerArgs
        {
            [DataMember(Name = "input")]
            public InputState Input;
            [DataMember(Name = "client_pos")]
            public Vector3 ClientPos;
            [DataMember(Name = "client_rot")]
            public Vector3 ClientRot;
            [DataMember(Name = "client_animation")]
            public string ClientAnimation;

            public UpdatePlayerInput(
                InputState Input,
                Vector3 ClientPos,
                Vector3 ClientRot,
                string ClientAnimation
            )
            {
                this.Input = Input;
                this.ClientPos = ClientPos;
                this.ClientRot = ClientRot;
                this.ClientAnimation = ClientAnimation;
            }

            public UpdatePlayerInput()
            {
                this.Input = new();
                this.ClientPos = new();
                this.ClientRot = new();
                this.ClientAnimation = "";
            }

            string IReducerArgs.ReducerName => "update_player_input";
        }
    }
}
