// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WriteBillionaireWhisperHandler(ReducerEventContext ctx, SpacetimeDB.Identity target, SpacetimeDB.Identity? about, string text);
        public event WriteBillionaireWhisperHandler? OnWriteBillionaireWhisper;

        public void WriteBillionaireWhisper(SpacetimeDB.Identity target, SpacetimeDB.Identity? about, string text)
        {
            conn.InternalCallReducer(new Reducer.WriteBillionaireWhisper(target, about, text));
        }

        public bool InvokeWriteBillionaireWhisper(ReducerEventContext ctx, Reducer.WriteBillionaireWhisper args)
        {
            if (OnWriteBillionaireWhisper == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnWriteBillionaireWhisper(
                ctx,
                args.Target,
                args.About,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WriteBillionaireWhisper : Reducer, IReducerArgs
        {
            [DataMember(Name = "target")]
            public SpacetimeDB.Identity Target;
            [DataMember(Name = "about")]
            public SpacetimeDB.Identity? About;
            [DataMember(Name = "text")]
            public string Text;

            public WriteBillionaireWhisper(
                SpacetimeDB.Identity Target,
                SpacetimeDB.Identity? About,
                string Text
            )
            {
                this.Target = Target;
                this.About = About;
                this.Text = Text;
            }

            public WriteBillionaireWhisper()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "write_billionaire_whisper";
        }
    }
}
