// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WriteLobbyHooksHandler(ReducerEventContext ctx, ulong runId, System.Collections.Generic.List<SpacetimeDB.Types.HookSpec> hooks);
        public event WriteLobbyHooksHandler? OnWriteLobbyHooks;

        public void WriteLobbyHooks(ulong runId, System.Collections.Generic.List<SpacetimeDB.Types.HookSpec> hooks)
        {
            conn.InternalCallReducer(new Reducer.WriteLobbyHooks(runId, hooks));
        }

        public bool InvokeWriteLobbyHooks(ReducerEventContext ctx, Reducer.WriteLobbyHooks args)
        {
            if (OnWriteLobbyHooks == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnWriteLobbyHooks(
                ctx,
                args.RunId,
                args.Hooks
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WriteLobbyHooks : Reducer, IReducerArgs
        {
            [DataMember(Name = "run_id")]
            public ulong RunId;
            [DataMember(Name = "hooks")]
            public System.Collections.Generic.List<HookSpec> Hooks;

            public WriteLobbyHooks(
                ulong RunId,
                System.Collections.Generic.List<HookSpec> Hooks
            )
            {
                this.RunId = RunId;
                this.Hooks = Hooks;
            }

            public WriteLobbyHooks()
            {
                this.Hooks = new();
            }

            string IReducerArgs.ReducerName => "write_lobby_hooks";
        }
    }
}
