// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BillionaireCognition
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "persona")]
        public string Persona;
        [DataMember(Name = "memory")]
        public string Memory;
        [DataMember(Name = "voice_id")]
        public string VoiceId;
        [DataMember(Name = "composure")]
        public int Composure;
        [DataMember(Name = "hidden_truth")]
        public string HiddenTruth;
        [DataMember(Name = "resentment")]
        public int Resentment;
        [DataMember(Name = "director_identity")]
        public SpacetimeDB.Identity DirectorIdentity;

        public BillionaireCognition(
            uint Id,
            string Persona,
            string Memory,
            string VoiceId,
            int Composure,
            string HiddenTruth,
            int Resentment,
            SpacetimeDB.Identity DirectorIdentity
        )
        {
            this.Id = Id;
            this.Persona = Persona;
            this.Memory = Memory;
            this.VoiceId = VoiceId;
            this.Composure = Composure;
            this.HiddenTruth = HiddenTruth;
            this.Resentment = Resentment;
            this.DirectorIdentity = DirectorIdentity;
        }

        public BillionaireCognition()
        {
            this.Persona = "";
            this.Memory = "";
            this.VoiceId = "";
            this.HiddenTruth = "";
        }
    }
}
