// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ForestEvent
    {
        [DataMember(Name = "event_id")]
        public ulong EventId;
        [DataMember(Name = "player_identity")]
        public SpacetimeDB.Identity PlayerIdentity;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "run_id")]
        public ulong RunId;
        [DataMember(Name = "detail")]
        public string Detail;
        [DataMember(Name = "created_tick")]
        public long CreatedTick;

        public ForestEvent(
            ulong EventId,
            SpacetimeDB.Identity PlayerIdentity,
            string Kind,
            ulong RunId,
            string Detail,
            long CreatedTick
        )
        {
            this.EventId = EventId;
            this.PlayerIdentity = PlayerIdentity;
            this.Kind = Kind;
            this.RunId = RunId;
            this.Detail = Detail;
            this.CreatedTick = CreatedTick;
        }

        public ForestEvent()
        {
            this.Kind = "";
            this.Detail = "";
        }
    }
}
