// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InputState
    {
        [DataMember(Name = "forward")]
        public bool Forward;
        [DataMember(Name = "backward")]
        public bool Backward;
        [DataMember(Name = "left")]
        public bool Left;
        [DataMember(Name = "right")]
        public bool Right;
        [DataMember(Name = "sprint")]
        public bool Sprint;
        [DataMember(Name = "jump")]
        public bool Jump;
        [DataMember(Name = "attack")]
        public bool Attack;
        [DataMember(Name = "cast_spell")]
        public bool CastSpell;
        [DataMember(Name = "sequence")]
        public uint Sequence;

        public InputState(
            bool Forward,
            bool Backward,
            bool Left,
            bool Right,
            bool Sprint,
            bool Jump,
            bool Attack,
            bool CastSpell,
            uint Sequence
        )
        {
            this.Forward = Forward;
            this.Backward = Backward;
            this.Left = Left;
            this.Right = Right;
            this.Sprint = Sprint;
            this.Jump = Jump;
            this.Attack = Attack;
            this.CastSpell = CastSpell;
            this.Sequence = Sequence;
        }

        public InputState()
        {
        }
    }
}
