// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LobbyHookTruth
    {
        [DataMember(Name = "hook_id")]
        public ulong HookId;
        [DataMember(Name = "is_lie")]
        public bool IsLie;
        [DataMember(Name = "real_truth")]
        public string RealTruth;

        public LobbyHookTruth(
            ulong HookId,
            bool IsLie,
            string RealTruth
        )
        {
            this.HookId = HookId;
            this.IsLie = IsLie;
            this.RealTruth = RealTruth;
        }

        public LobbyHookTruth()
        {
            this.RealTruth = "";
        }
    }
}
