// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LobbyCharacterCatalog
    {
        [DataMember(Name = "character_id")]
        public uint CharacterId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "archetype")]
        public string Archetype;
        [DataMember(Name = "model_key")]
        public string ModelKey;
        [DataMember(Name = "blurb")]
        public string Blurb;

        public LobbyCharacterCatalog(
            uint CharacterId,
            string DisplayName,
            string Archetype,
            string ModelKey,
            string Blurb
        )
        {
            this.CharacterId = CharacterId;
            this.DisplayName = DisplayName;
            this.Archetype = Archetype;
            this.ModelKey = ModelKey;
            this.Blurb = Blurb;
        }

        public LobbyCharacterCatalog()
        {
            this.DisplayName = "";
            this.Archetype = "";
            this.ModelKey = "";
            this.Blurb = "";
        }
    }
}
