// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PartyChat
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "body")]
        public string Body;
        [DataMember(Name = "created_tick")]
        public long CreatedTick;
        [DataMember(Name = "is_billionaire")]
        public bool IsBillionaire;
        [DataMember(Name = "addressed_billionaire")]
        public bool AddressedBillionaire;
        [DataMember(Name = "party_id")]
        public string PartyId;

        public PartyChat(
            ulong Id,
            SpacetimeDB.Identity Sender,
            string SenderName,
            string Body,
            long CreatedTick,
            bool IsBillionaire,
            bool AddressedBillionaire,
            string PartyId
        )
        {
            this.Id = Id;
            this.Sender = Sender;
            this.SenderName = SenderName;
            this.Body = Body;
            this.CreatedTick = CreatedTick;
            this.IsBillionaire = IsBillionaire;
            this.AddressedBillionaire = AddressedBillionaire;
            this.PartyId = PartyId;
        }

        public PartyChat()
        {
            this.SenderName = "";
            this.Body = "";
            this.PartyId = "";
        }
    }
}
