// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerData
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "character_class")]
        public string CharacterClass;
        [DataMember(Name = "position")]
        public Vector3 Position;
        [DataMember(Name = "rotation")]
        public Vector3 Rotation;
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "mana")]
        public int Mana;
        [DataMember(Name = "max_mana")]
        public int MaxMana;
        [DataMember(Name = "current_animation")]
        public string CurrentAnimation;
        [DataMember(Name = "is_moving")]
        public bool IsMoving;
        [DataMember(Name = "is_running")]
        public bool IsRunning;
        [DataMember(Name = "is_attacking")]
        public bool IsAttacking;
        [DataMember(Name = "is_casting")]
        public bool IsCasting;
        [DataMember(Name = "last_input_seq")]
        public uint LastInputSeq;
        [DataMember(Name = "input")]
        public InputState Input;
        [DataMember(Name = "color")]
        public string Color;

        public PlayerData(
            SpacetimeDB.Identity Identity,
            string Username,
            string CharacterClass,
            Vector3 Position,
            Vector3 Rotation,
            int Health,
            int MaxHealth,
            int Mana,
            int MaxMana,
            string CurrentAnimation,
            bool IsMoving,
            bool IsRunning,
            bool IsAttacking,
            bool IsCasting,
            uint LastInputSeq,
            InputState Input,
            string Color
        )
        {
            this.Identity = Identity;
            this.Username = Username;
            this.CharacterClass = CharacterClass;
            this.Position = Position;
            this.Rotation = Rotation;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.Mana = Mana;
            this.MaxMana = MaxMana;
            this.CurrentAnimation = CurrentAnimation;
            this.IsMoving = IsMoving;
            this.IsRunning = IsRunning;
            this.IsAttacking = IsAttacking;
            this.IsCasting = IsCasting;
            this.LastInputSeq = LastInputSeq;
            this.Input = Input;
            this.Color = Color;
        }

        public PlayerData()
        {
            this.Username = "";
            this.CharacterClass = "";
            this.Position = new();
            this.Rotation = new();
            this.CurrentAnimation = "";
            this.Input = new();
            this.Color = "";
        }
    }
}
