// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldState
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "now_tick")]
        public long NowTick;
        [DataMember(Name = "time_of_day")]
        public string TimeOfDay;
        [DataMember(Name = "weather_conditions")]
        public string WeatherConditions;
        [DataMember(Name = "patron_dread")]
        public int PatronDread;

        public WorldState(
            uint Id,
            long NowTick,
            string TimeOfDay,
            string WeatherConditions,
            int PatronDread
        )
        {
            this.Id = Id;
            this.NowTick = NowTick;
            this.TimeOfDay = TimeOfDay;
            this.WeatherConditions = WeatherConditions;
            this.PatronDread = PatronDread;
        }

        public WorldState()
        {
            this.TimeOfDay = "";
            this.WeatherConditions = "";
        }
    }
}
