// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BillionaireRespondHandler(ReducerEventContext ctx, ulong requestId, string dialogue, string animationTrigger, string mood, SpacetimeDB.Identity? targetMember, string kind, int composureChange);
        public event BillionaireRespondHandler? OnBillionaireRespond;

        public void BillionaireRespond(ulong requestId, string dialogue, string animationTrigger, string mood, SpacetimeDB.Identity? targetMember, string kind, int composureChange)
        {
            conn.InternalCallReducer(new Reducer.BillionaireRespond(requestId, dialogue, animationTrigger, mood, targetMember, kind, composureChange));
        }

        public bool InvokeBillionaireRespond(ReducerEventContext ctx, Reducer.BillionaireRespond args)
        {
            if (OnBillionaireRespond == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBillionaireRespond(
                ctx,
                args.RequestId,
                args.Dialogue,
                args.AnimationTrigger,
                args.Mood,
                args.TargetMember,
                args.Kind,
                args.ComposureChange
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BillionaireRespond : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;
            [DataMember(Name = "dialogue")]
            public string Dialogue;
            [DataMember(Name = "animation_trigger")]
            public string AnimationTrigger;
            [DataMember(Name = "mood")]
            public string Mood;
            [DataMember(Name = "target_member")]
            public SpacetimeDB.Identity? TargetMember;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "composure_change")]
            public int ComposureChange;

            public BillionaireRespond(
                ulong RequestId,
                string Dialogue,
                string AnimationTrigger,
                string Mood,
                SpacetimeDB.Identity? TargetMember,
                string Kind,
                int ComposureChange
            )
            {
                this.RequestId = RequestId;
                this.Dialogue = Dialogue;
                this.AnimationTrigger = AnimationTrigger;
                this.Mood = Mood;
                this.TargetMember = TargetMember;
                this.Kind = Kind;
                this.ComposureChange = ComposureChange;
            }

            public BillionaireRespond()
            {
                this.Dialogue = "";
                this.AnimationTrigger = "";
                this.Mood = "";
                this.Kind = "";
            }

            string IReducerArgs.ReducerName => "billionaire_respond";
        }
    }
}
