// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimInteractionHandler(ReducerEventContext ctx, ulong interactionId);
        public event ClaimInteractionHandler? OnClaimInteraction;

        public void ClaimInteraction(ulong interactionId)
        {
            conn.InternalCallReducer(new Reducer.ClaimInteraction(interactionId));
        }

        public bool InvokeClaimInteraction(ReducerEventContext ctx, Reducer.ClaimInteraction args)
        {
            if (OnClaimInteraction == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimInteraction(
                ctx,
                args.InteractionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimInteraction : Reducer, IReducerArgs
        {
            [DataMember(Name = "interaction_id")]
            public ulong InteractionId;

            public ClaimInteraction(ulong InteractionId)
            {
                this.InteractionId = InteractionId;
            }

            public ClaimInteraction()
            {
            }

            string IReducerArgs.ReducerName => "claim_interaction";
        }
    }
}
