// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmitForestEventHandler(ReducerEventContext ctx, SpacetimeDB.Identity playerIdentity, string kind, string detail);
        public event EmitForestEventHandler? OnEmitForestEvent;

        public void EmitForestEvent(SpacetimeDB.Identity playerIdentity, string kind, string detail)
        {
            conn.InternalCallReducer(new Reducer.EmitForestEvent(playerIdentity, kind, detail));
        }

        public bool InvokeEmitForestEvent(ReducerEventContext ctx, Reducer.EmitForestEvent args)
        {
            if (OnEmitForestEvent == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmitForestEvent(
                ctx,
                args.PlayerIdentity,
                args.Kind,
                args.Detail
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmitForestEvent : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_identity")]
            public SpacetimeDB.Identity PlayerIdentity;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "detail")]
            public string Detail;

            public EmitForestEvent(
                SpacetimeDB.Identity PlayerIdentity,
                string Kind,
                string Detail
            )
            {
                this.PlayerIdentity = PlayerIdentity;
                this.Kind = Kind;
                this.Detail = Detail;
            }

            public EmitForestEvent()
            {
                this.Kind = "";
                this.Detail = "";
            }

            string IReducerArgs.ReducerName => "emit_forest_event";
        }
    }
}
