// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void FailInteractionHandler(ReducerEventContext ctx, ulong interactionId, string reason);
        public event FailInteractionHandler? OnFailInteraction;

        public void FailInteraction(ulong interactionId, string reason)
        {
            conn.InternalCallReducer(new Reducer.FailInteraction(interactionId, reason));
        }

        public bool InvokeFailInteraction(ReducerEventContext ctx, Reducer.FailInteraction args)
        {
            if (OnFailInteraction == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnFailInteraction(
                ctx,
                args.InteractionId,
                args.Reason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class FailInteraction : Reducer, IReducerArgs
        {
            [DataMember(Name = "interaction_id")]
            public ulong InteractionId;
            [DataMember(Name = "reason")]
            public string Reason;

            public FailInteraction(
                ulong InteractionId,
                string Reason
            )
            {
                this.InteractionId = InteractionId;
                this.Reason = Reason;
            }

            public FailInteraction()
            {
                this.Reason = "";
            }

            string IReducerArgs.ReducerName => "fail_interaction";
        }
    }
}
