// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinPartyHandler(ReducerEventContext ctx, string code);
        public event JoinPartyHandler? OnJoinParty;

        public void JoinParty(string code)
        {
            conn.InternalCallReducer(new Reducer.JoinParty(code));
        }

        public bool InvokeJoinParty(ReducerEventContext ctx, Reducer.JoinParty args)
        {
            if (OnJoinParty == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinParty(
                ctx,
                args.Code
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinParty : Reducer, IReducerArgs
        {
            [DataMember(Name = "code")]
            public string Code;

            public JoinParty(string Code)
            {
                this.Code = Code;
            }

            public JoinParty()
            {
                this.Code = "";
            }

            string IReducerArgs.ReducerName => "join_party";
        }
    }
}
