// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendChatHandler(ReducerEventContext ctx, string body);
        public event SendChatHandler? OnSendChat;

        public void SendChat(string body)
        {
            conn.InternalCallReducer(new Reducer.SendChat(body));
        }

        public bool InvokeSendChat(ReducerEventContext ctx, Reducer.SendChat args)
        {
            if (OnSendChat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendChat(
                ctx,
                args.Body
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendChat : Reducer, IReducerArgs
        {
            [DataMember(Name = "body")]
            public string Body;

            public SendChat(string Body)
            {
                this.Body = Body;
            }

            public SendChat()
            {
                this.Body = "";
            }

            string IReducerArgs.ReducerName => "send_chat";
        }
    }
}
