// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetCharacterHandler(ReducerEventContext ctx, uint characterId);
        public event SetCharacterHandler? OnSetCharacter;

        public void SetCharacter(uint characterId)
        {
            conn.InternalCallReducer(new Reducer.SetCharacter(characterId));
        }

        public bool InvokeSetCharacter(ReducerEventContext ctx, Reducer.SetCharacter args)
        {
            if (OnSetCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetCharacter(
                ctx,
                args.CharacterId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "character_id")]
            public uint CharacterId;

            public SetCharacter(uint CharacterId)
            {
                this.CharacterId = CharacterId;
            }

            public SetCharacter()
            {
            }

            string IReducerArgs.ReducerName => "set_character";
        }
    }
}
