// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetFavorHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.FavorDelta> deltas);
        public event SetFavorHandler? OnSetFavor;

        public void SetFavor(System.Collections.Generic.List<SpacetimeDB.Types.FavorDelta> deltas)
        {
            conn.InternalCallReducer(new Reducer.SetFavor(deltas));
        }

        public bool InvokeSetFavor(ReducerEventContext ctx, Reducer.SetFavor args)
        {
            if (OnSetFavor == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetFavor(
                ctx,
                args.Deltas
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetFavor : Reducer, IReducerArgs
        {
            [DataMember(Name = "deltas")]
            public System.Collections.Generic.List<FavorDelta> Deltas;

            public SetFavor(System.Collections.Generic.List<FavorDelta> Deltas)
            {
                this.Deltas = Deltas;
            }

            public SetFavor()
            {
                this.Deltas = new();
            }

            string IReducerArgs.ReducerName => "set_favor";
        }
    }
}
