// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetOddsHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.OddsUpdate> updates);
        public event SetOddsHandler? OnSetOdds;

        public void SetOdds(System.Collections.Generic.List<SpacetimeDB.Types.OddsUpdate> updates)
        {
            conn.InternalCallReducer(new Reducer.SetOdds(updates));
        }

        public bool InvokeSetOdds(ReducerEventContext ctx, Reducer.SetOdds args)
        {
            if (OnSetOdds == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetOdds(
                ctx,
                args.Updates
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetOdds : Reducer, IReducerArgs
        {
            [DataMember(Name = "updates")]
            public System.Collections.Generic.List<OddsUpdate> Updates;

            public SetOdds(System.Collections.Generic.List<OddsUpdate> Updates)
            {
                this.Updates = Updates;
            }

            public SetOdds()
            {
                this.Updates = new();
            }

            string IReducerArgs.ReducerName => "set_odds";
        }
    }
}
