// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPatronDreadHandler(ReducerEventContext ctx, int dread);
        public event SetPatronDreadHandler? OnSetPatronDread;

        public void SetPatronDread(int dread)
        {
            conn.InternalCallReducer(new Reducer.SetPatronDread(dread));
        }

        public bool InvokeSetPatronDread(ReducerEventContext ctx, Reducer.SetPatronDread args)
        {
            if (OnSetPatronDread == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetPatronDread(
                ctx,
                args.Dread
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPatronDread : Reducer, IReducerArgs
        {
            [DataMember(Name = "dread")]
            public int Dread;

            public SetPatronDread(int Dread)
            {
                this.Dread = Dread;
            }

            public SetPatronDread()
            {
            }

            string IReducerArgs.ReducerName => "set_patron_dread";
        }
    }
}
