// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateBillionaireMemoryHandler(ReducerEventContext ctx, string memory);
        public event UpdateBillionaireMemoryHandler? OnUpdateBillionaireMemory;

        public void UpdateBillionaireMemory(string memory)
        {
            conn.InternalCallReducer(new Reducer.UpdateBillionaireMemory(memory));
        }

        public bool InvokeUpdateBillionaireMemory(ReducerEventContext ctx, Reducer.UpdateBillionaireMemory args)
        {
            if (OnUpdateBillionaireMemory == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateBillionaireMemory(
                ctx,
                args.Memory
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateBillionaireMemory : Reducer, IReducerArgs
        {
            [DataMember(Name = "memory")]
            public string Memory;

            public UpdateBillionaireMemory(string Memory)
            {
                this.Memory = Memory;
            }

            public UpdateBillionaireMemory()
            {
                this.Memory = "";
            }

            string IReducerArgs.ReducerName => "update_billionaire_memory";
        }
    }
}
