// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateDossierHandler(ReducerEventContext ctx, string usernameKey, string nickname, string dossierText, int grudgeDelta, int runsDelta);
        public event UpdateDossierHandler? OnUpdateDossier;

        public void UpdateDossier(string usernameKey, string nickname, string dossierText, int grudgeDelta, int runsDelta)
        {
            conn.InternalCallReducer(new Reducer.UpdateDossier(usernameKey, nickname, dossierText, grudgeDelta, runsDelta));
        }

        public bool InvokeUpdateDossier(ReducerEventContext ctx, Reducer.UpdateDossier args)
        {
            if (OnUpdateDossier == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateDossier(
                ctx,
                args.UsernameKey,
                args.Nickname,
                args.DossierText,
                args.GrudgeDelta,
                args.RunsDelta
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateDossier : Reducer, IReducerArgs
        {
            [DataMember(Name = "username_key")]
            public string UsernameKey;
            [DataMember(Name = "nickname")]
            public string Nickname;
            [DataMember(Name = "dossier_text")]
            public string DossierText;
            [DataMember(Name = "grudge_delta")]
            public int GrudgeDelta;
            [DataMember(Name = "runs_delta")]
            public int RunsDelta;

            public UpdateDossier(
                string UsernameKey,
                string Nickname,
                string DossierText,
                int GrudgeDelta,
                int RunsDelta
            )
            {
                this.UsernameKey = UsernameKey;
                this.Nickname = Nickname;
                this.DossierText = DossierText;
                this.GrudgeDelta = GrudgeDelta;
                this.RunsDelta = RunsDelta;
            }

            public UpdateDossier()
            {
                this.UsernameKey = "";
                this.Nickname = "";
                this.DossierText = "";
            }

            string IReducerArgs.ReducerName => "update_dossier";
        }
    }
}
