// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClueHandle : RemoteTableHandle<EventContext, Clue>
        {
            protected override string RemoteTableName => "clue";

            public sealed class CodeIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(Clue row) => row.Code;

                public CodeIndex(ClueHandle table) : base(table) { }
            }

            public readonly CodeIndex Code;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Clue row) => row.Id;

                public IdUniqueIndex(ClueHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ClueHandle(DbConnection conn) : base(conn)
            {
                Code = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(Clue row) => row.Id;
        }

        public readonly ClueHandle Clue;
    }

    public sealed class ClueCols
    {
        public global::SpacetimeDB.Col<Clue, ulong> Id { get; }
        public global::SpacetimeDB.Col<Clue, string> Code { get; }
        public global::SpacetimeDB.Col<Clue, string> FactText { get; }
        public global::SpacetimeDB.Col<Clue, string> Truth { get; }
        public global::SpacetimeDB.Col<Clue, ulong> OverriddenByClueId { get; }
        public global::SpacetimeDB.Col<Clue, uint> Act { get; }
        public global::SpacetimeDB.Col<Clue, string> PointsTo { get; }

        public ClueCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Clue, ulong>(tableName, "id");
            Code = new global::SpacetimeDB.Col<Clue, string>(tableName, "code");
            FactText = new global::SpacetimeDB.Col<Clue, string>(tableName, "fact_text");
            Truth = new global::SpacetimeDB.Col<Clue, string>(tableName, "truth");
            OverriddenByClueId = new global::SpacetimeDB.Col<Clue, ulong>(tableName, "overridden_by_clue_id");
            Act = new global::SpacetimeDB.Col<Clue, uint>(tableName, "act");
            PointsTo = new global::SpacetimeDB.Col<Clue, string>(tableName, "points_to");
        }
    }

    public sealed class ClueIxCols
    {
        public global::SpacetimeDB.IxCol<Clue, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Clue, string> Code { get; }

        public ClueIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Clue, ulong>(tableName, "id");
            Code = new global::SpacetimeDB.IxCol<Clue, string>(tableName, "code");
        }
    }
}
