// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClueComboHandle : RemoteTableHandle<EventContext, ClueCombo>
        {
            protected override string RemoteTableName => "clue_combo";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClueCombo row) => row.Id;

                public IdUniqueIndex(ClueComboHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ClueComboHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ClueCombo row) => row.Id;
        }

        public readonly ClueComboHandle ClueCombo;
    }

    public sealed class ClueComboCols
    {
        public global::SpacetimeDB.Col<ClueCombo, ulong> Id { get; }
        public global::SpacetimeDB.Col<ClueCombo, System.Collections.Generic.List<ulong>> RequiredClueIds { get; }
        public global::SpacetimeDB.Col<ClueCombo, ulong> YieldsClueId { get; }
        public global::SpacetimeDB.Col<ClueCombo, bool> IsActGoal { get; }
        public global::SpacetimeDB.Col<ClueCombo, uint> Act { get; }

        public ClueComboCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ClueCombo, ulong>(tableName, "id");
            RequiredClueIds = new global::SpacetimeDB.Col<ClueCombo, System.Collections.Generic.List<ulong>>(tableName, "required_clue_ids");
            YieldsClueId = new global::SpacetimeDB.Col<ClueCombo, ulong>(tableName, "yields_clue_id");
            IsActGoal = new global::SpacetimeDB.Col<ClueCombo, bool>(tableName, "is_act_goal");
            Act = new global::SpacetimeDB.Col<ClueCombo, uint>(tableName, "act");
        }
    }

    public sealed class ClueComboIxCols
    {
        public global::SpacetimeDB.IxCol<ClueCombo, ulong> Id { get; }

        public ClueComboIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ClueCombo, ulong>(tableName, "id");
        }
    }
}
