// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClueRevealHandle : RemoteTableHandle<EventContext, ClueReveal>
        {
            protected override string RemoteTableName => "clue_reveal";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClueReveal row) => row.Id;

                public IdUniqueIndex(ClueRevealHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RunIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ClueReveal row) => row.RunId;

                public RunIdIndex(ClueRevealHandle table) : base(table) { }
            }

            public readonly RunIdIndex RunId;

            internal ClueRevealHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RunId = new(this);
            }

            protected override object GetPrimaryKey(ClueReveal row) => row.Id;
        }

        public readonly ClueRevealHandle ClueReveal;
    }

    public sealed class ClueRevealCols
    {
        public global::SpacetimeDB.Col<ClueReveal, ulong> Id { get; }
        public global::SpacetimeDB.Col<ClueReveal, ulong> RunId { get; }
        public global::SpacetimeDB.Col<ClueReveal, string> ClueCode { get; }
        public global::SpacetimeDB.Col<ClueReveal, string> FactText { get; }
        public global::SpacetimeDB.Col<ClueReveal, uint> Act { get; }

        public ClueRevealCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ClueReveal, ulong>(tableName, "id");
            RunId = new global::SpacetimeDB.Col<ClueReveal, ulong>(tableName, "run_id");
            ClueCode = new global::SpacetimeDB.Col<ClueReveal, string>(tableName, "clue_code");
            FactText = new global::SpacetimeDB.Col<ClueReveal, string>(tableName, "fact_text");
            Act = new global::SpacetimeDB.Col<ClueReveal, uint>(tableName, "act");
        }
    }

    public sealed class ClueRevealIxCols
    {
        public global::SpacetimeDB.IxCol<ClueReveal, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ClueReveal, ulong> RunId { get; }

        public ClueRevealIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ClueReveal, ulong>(tableName, "id");
            RunId = new global::SpacetimeDB.IxCol<ClueReveal, ulong>(tableName, "run_id");
        }
    }
}
