// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LobbyMemberHandle : RemoteTableHandle<EventContext, LobbyMember>
        {
            protected override string RemoteTableName => "lobby_member";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(LobbyMember row) => row.Identity;

                public IdentityUniqueIndex(LobbyMemberHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class PartyIdIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(LobbyMember row) => row.PartyId;

                public PartyIdIndex(LobbyMemberHandle table) : base(table) { }
            }

            public readonly PartyIdIndex PartyId;

            internal LobbyMemberHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                PartyId = new(this);
            }

            protected override object GetPrimaryKey(LobbyMember row) => row.Identity;
        }

        public readonly LobbyMemberHandle LobbyMember;
    }

    public sealed class LobbyMemberCols
    {
        public global::SpacetimeDB.Col<LobbyMember, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> Username { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> Nickname { get; }
        public global::SpacetimeDB.Col<LobbyMember, uint> CharacterId { get; }
        public global::SpacetimeDB.Col<LobbyMember, bool> IsReady { get; }
        public global::SpacetimeDB.Col<LobbyMember, long> ReadyTick { get; }
        public global::SpacetimeDB.Col<LobbyMember, long> LastActivityTick { get; }
        public global::SpacetimeDB.Col<LobbyMember, uint> SwapCount { get; }
        public global::SpacetimeDB.Col<LobbyMember, uint> Slot { get; }
        public global::SpacetimeDB.Col<LobbyMember, uint> Seq { get; }
        public global::SpacetimeDB.Col<LobbyMember, int> SurvivalPct { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> DeathPrediction { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> CallbackTag { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> Allegiance { get; }
        public global::SpacetimeDB.Col<LobbyMember, int> Favor { get; }
        public global::SpacetimeDB.Col<LobbyMember, bool> IsExpeditionLead { get; }
        public global::SpacetimeDB.Col<LobbyMember, bool> IsLiability { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> WhisperText { get; }
        public global::SpacetimeDB.Col<LobbyMember, SpacetimeDB.Identity> WhisperAbout { get; }
        public global::SpacetimeDB.Col<LobbyMember, uint> WhisperSeq { get; }
        public global::SpacetimeDB.Col<LobbyMember, string> PartyId { get; }

        public LobbyMemberCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<LobbyMember, SpacetimeDB.Identity>(tableName, "identity");
            Username = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "username");
            Nickname = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "nickname");
            CharacterId = new global::SpacetimeDB.Col<LobbyMember, uint>(tableName, "character_id");
            IsReady = new global::SpacetimeDB.Col<LobbyMember, bool>(tableName, "is_ready");
            ReadyTick = new global::SpacetimeDB.Col<LobbyMember, long>(tableName, "ready_tick");
            LastActivityTick = new global::SpacetimeDB.Col<LobbyMember, long>(tableName, "last_activity_tick");
            SwapCount = new global::SpacetimeDB.Col<LobbyMember, uint>(tableName, "swap_count");
            Slot = new global::SpacetimeDB.Col<LobbyMember, uint>(tableName, "slot");
            Seq = new global::SpacetimeDB.Col<LobbyMember, uint>(tableName, "seq");
            SurvivalPct = new global::SpacetimeDB.Col<LobbyMember, int>(tableName, "survival_pct");
            DeathPrediction = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "death_prediction");
            CallbackTag = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "callback_tag");
            Allegiance = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "allegiance");
            Favor = new global::SpacetimeDB.Col<LobbyMember, int>(tableName, "favor");
            IsExpeditionLead = new global::SpacetimeDB.Col<LobbyMember, bool>(tableName, "is_expedition_lead");
            IsLiability = new global::SpacetimeDB.Col<LobbyMember, bool>(tableName, "is_liability");
            WhisperText = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "whisper_text");
            WhisperAbout = new global::SpacetimeDB.Col<LobbyMember, SpacetimeDB.Identity>(tableName, "whisper_about");
            WhisperSeq = new global::SpacetimeDB.Col<LobbyMember, uint>(tableName, "whisper_seq");
            PartyId = new global::SpacetimeDB.Col<LobbyMember, string>(tableName, "party_id");
        }
    }

    public sealed class LobbyMemberIxCols
    {
        public global::SpacetimeDB.IxCol<LobbyMember, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<LobbyMember, string> PartyId { get; }

        public LobbyMemberIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<LobbyMember, SpacetimeDB.Identity>(tableName, "identity");
            PartyId = new global::SpacetimeDB.IxCol<LobbyMember, string>(tableName, "party_id");
        }
    }
}
