// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LobbyCharacterCatalogHandle : RemoteTableHandle<EventContext, LobbyCharacterCatalog>
        {
            protected override string RemoteTableName => "lobby_character_catalog";

            public sealed class CharacterIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(LobbyCharacterCatalog row) => row.CharacterId;

                public CharacterIdUniqueIndex(LobbyCharacterCatalogHandle table) : base(table) { }
            }

            public readonly CharacterIdUniqueIndex CharacterId;

            internal LobbyCharacterCatalogHandle(DbConnection conn) : base(conn)
            {
                CharacterId = new(this);
            }

            protected override object GetPrimaryKey(LobbyCharacterCatalog row) => row.CharacterId;
        }

        public readonly LobbyCharacterCatalogHandle LobbyCharacterCatalog;
    }

    public sealed class LobbyCharacterCatalogCols
    {
        public global::SpacetimeDB.Col<LobbyCharacterCatalog, uint> CharacterId { get; }
        public global::SpacetimeDB.Col<LobbyCharacterCatalog, string> DisplayName { get; }
        public global::SpacetimeDB.Col<LobbyCharacterCatalog, string> Archetype { get; }
        public global::SpacetimeDB.Col<LobbyCharacterCatalog, string> ModelKey { get; }
        public global::SpacetimeDB.Col<LobbyCharacterCatalog, string> Blurb { get; }

        public LobbyCharacterCatalogCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.Col<LobbyCharacterCatalog, uint>(tableName, "character_id");
            DisplayName = new global::SpacetimeDB.Col<LobbyCharacterCatalog, string>(tableName, "display_name");
            Archetype = new global::SpacetimeDB.Col<LobbyCharacterCatalog, string>(tableName, "archetype");
            ModelKey = new global::SpacetimeDB.Col<LobbyCharacterCatalog, string>(tableName, "model_key");
            Blurb = new global::SpacetimeDB.Col<LobbyCharacterCatalog, string>(tableName, "blurb");
        }
    }

    public sealed class LobbyCharacterCatalogIxCols
    {
        public global::SpacetimeDB.IxCol<LobbyCharacterCatalog, uint> CharacterId { get; }

        public LobbyCharacterCatalogIxCols(string tableName)
        {
            CharacterId = new global::SpacetimeDB.IxCol<LobbyCharacterCatalog, uint>(tableName, "character_id");
        }
    }
}
