// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcHandle : RemoteTableHandle<EventContext, Npc>
        {
            protected override string RemoteTableName => "npc";

            public sealed class NpcIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Npc row) => row.NpcId;

                public NpcIdUniqueIndex(NpcHandle table) : base(table) { }
            }

            public readonly NpcIdUniqueIndex NpcId;

            internal NpcHandle(DbConnection conn) : base(conn)
            {
                NpcId = new(this);
            }

            protected override object GetPrimaryKey(Npc row) => row.NpcId;
        }

        public readonly NpcHandle Npc;
    }

    public sealed class NpcCols
    {
        public global::SpacetimeDB.Col<Npc, ulong> NpcId { get; }
        public global::SpacetimeDB.Col<Npc, string> DisplayName { get; }
        public global::SpacetimeDB.Col<Npc, string> Archetype { get; }
        public global::SpacetimeDB.Col<Npc, Vector3> Position { get; }
        public global::SpacetimeDB.Col<Npc, string> Dialogue { get; }
        public global::SpacetimeDB.Col<Npc, string> AnimationTrigger { get; }
        public global::SpacetimeDB.Col<Npc, string> GameAction { get; }
        public global::SpacetimeDB.Col<Npc, SpacetimeDB.Identity> TargetPlayer { get; }
        public global::SpacetimeDB.Col<Npc, int> Trust { get; }
        public global::SpacetimeDB.Col<Npc, int> Sanity { get; }
        public global::SpacetimeDB.Col<Npc, uint> Seq { get; }
        public global::SpacetimeDB.Col<Npc, long> LastSpokeTick { get; }
        public global::SpacetimeDB.Col<Npc, long> BusyUntilTick { get; }
        public global::SpacetimeDB.Col<Npc, ulong> BusyInteractionId { get; }

        public NpcCols(string tableName)
        {
            NpcId = new global::SpacetimeDB.Col<Npc, ulong>(tableName, "npc_id");
            DisplayName = new global::SpacetimeDB.Col<Npc, string>(tableName, "display_name");
            Archetype = new global::SpacetimeDB.Col<Npc, string>(tableName, "archetype");
            Position = new global::SpacetimeDB.Col<Npc, Vector3>(tableName, "position");
            Dialogue = new global::SpacetimeDB.Col<Npc, string>(tableName, "dialogue");
            AnimationTrigger = new global::SpacetimeDB.Col<Npc, string>(tableName, "animation_trigger");
            GameAction = new global::SpacetimeDB.Col<Npc, string>(tableName, "game_action");
            TargetPlayer = new global::SpacetimeDB.Col<Npc, SpacetimeDB.Identity>(tableName, "target_player");
            Trust = new global::SpacetimeDB.Col<Npc, int>(tableName, "trust");
            Sanity = new global::SpacetimeDB.Col<Npc, int>(tableName, "sanity");
            Seq = new global::SpacetimeDB.Col<Npc, uint>(tableName, "seq");
            LastSpokeTick = new global::SpacetimeDB.Col<Npc, long>(tableName, "last_spoke_tick");
            BusyUntilTick = new global::SpacetimeDB.Col<Npc, long>(tableName, "busy_until_tick");
            BusyInteractionId = new global::SpacetimeDB.Col<Npc, ulong>(tableName, "busy_interaction_id");
        }
    }

    public sealed class NpcIxCols
    {
        public global::SpacetimeDB.IxCol<Npc, ulong> NpcId { get; }

        public NpcIxCols(string tableName)
        {
            NpcId = new global::SpacetimeDB.IxCol<Npc, ulong>(tableName, "npc_id");
        }
    }
}
