// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcPlayerStateHandle : RemoteTableHandle<EventContext, NpcPlayerState>
        {
            protected override string RemoteTableName => "npc_player_state";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcPlayerState row) => row.Id;

                public IdUniqueIndex(NpcPlayerStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NpcIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(NpcPlayerState row) => row.NpcId;

                public NpcIdIndex(NpcPlayerStateHandle table) : base(table) { }
            }

            public readonly NpcIdIndex NpcId;

            public sealed class PlayerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(NpcPlayerState row) => row.Player;

                public PlayerIndex(NpcPlayerStateHandle table) : base(table) { }
            }

            public readonly PlayerIndex Player;

            internal NpcPlayerStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                NpcId = new(this);
                Player = new(this);
            }

            protected override object GetPrimaryKey(NpcPlayerState row) => row.Id;
        }

        public readonly NpcPlayerStateHandle NpcPlayerState;
    }

    public sealed class NpcPlayerStateCols
    {
        public global::SpacetimeDB.Col<NpcPlayerState, ulong> Id { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, ulong> NpcId { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, float> Trust { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, float> Fear { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, string> Flags { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, string> MemoryNote { get; }
        public global::SpacetimeDB.Col<NpcPlayerState, long> LastInteraction { get; }

        public NpcPlayerStateCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NpcPlayerState, ulong>(tableName, "id");
            NpcId = new global::SpacetimeDB.Col<NpcPlayerState, ulong>(tableName, "npc_id");
            Player = new global::SpacetimeDB.Col<NpcPlayerState, SpacetimeDB.Identity>(tableName, "player");
            Trust = new global::SpacetimeDB.Col<NpcPlayerState, float>(tableName, "trust");
            Fear = new global::SpacetimeDB.Col<NpcPlayerState, float>(tableName, "fear");
            Flags = new global::SpacetimeDB.Col<NpcPlayerState, string>(tableName, "flags");
            MemoryNote = new global::SpacetimeDB.Col<NpcPlayerState, string>(tableName, "memory_note");
            LastInteraction = new global::SpacetimeDB.Col<NpcPlayerState, long>(tableName, "last_interaction");
        }
    }

    public sealed class NpcPlayerStateIxCols
    {
        public global::SpacetimeDB.IxCol<NpcPlayerState, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<NpcPlayerState, ulong> NpcId { get; }
        public global::SpacetimeDB.IxCol<NpcPlayerState, SpacetimeDB.Identity> Player { get; }

        public NpcPlayerStateIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NpcPlayerState, ulong>(tableName, "id");
            NpcId = new global::SpacetimeDB.IxCol<NpcPlayerState, ulong>(tableName, "npc_id");
            Player = new global::SpacetimeDB.IxCol<NpcPlayerState, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
