// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PartyClueHandle : RemoteTableHandle<EventContext, PartyClue>
        {
            protected override string RemoteTableName => "party_clue";

            public sealed class ClueIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PartyClue row) => row.ClueId;

                public ClueIdIndex(PartyClueHandle table) : base(table) { }
            }

            public readonly ClueIdIndex ClueId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PartyClue row) => row.Id;

                public IdUniqueIndex(PartyClueHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RunIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PartyClue row) => row.RunId;

                public RunIdIndex(PartyClueHandle table) : base(table) { }
            }

            public readonly RunIdIndex RunId;

            internal PartyClueHandle(DbConnection conn) : base(conn)
            {
                ClueId = new(this);
                Id = new(this);
                RunId = new(this);
            }

            protected override object GetPrimaryKey(PartyClue row) => row.Id;
        }

        public readonly PartyClueHandle PartyClue;
    }

    public sealed class PartyClueCols
    {
        public global::SpacetimeDB.Col<PartyClue, ulong> Id { get; }
        public global::SpacetimeDB.Col<PartyClue, ulong> RunId { get; }
        public global::SpacetimeDB.Col<PartyClue, ulong> ClueId { get; }
        public global::SpacetimeDB.Col<PartyClue, ulong> RevealedByNpc { get; }
        public global::SpacetimeDB.Col<PartyClue, SpacetimeDB.Identity> RevealedTo { get; }

        public PartyClueCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PartyClue, ulong>(tableName, "id");
            RunId = new global::SpacetimeDB.Col<PartyClue, ulong>(tableName, "run_id");
            ClueId = new global::SpacetimeDB.Col<PartyClue, ulong>(tableName, "clue_id");
            RevealedByNpc = new global::SpacetimeDB.Col<PartyClue, ulong>(tableName, "revealed_by_npc");
            RevealedTo = new global::SpacetimeDB.Col<PartyClue, SpacetimeDB.Identity>(tableName, "revealed_to");
        }
    }

    public sealed class PartyClueIxCols
    {
        public global::SpacetimeDB.IxCol<PartyClue, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PartyClue, ulong> RunId { get; }
        public global::SpacetimeDB.IxCol<PartyClue, ulong> ClueId { get; }

        public PartyClueIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PartyClue, ulong>(tableName, "id");
            RunId = new global::SpacetimeDB.IxCol<PartyClue, ulong>(tableName, "run_id");
            ClueId = new global::SpacetimeDB.IxCol<PartyClue, ulong>(tableName, "clue_id");
        }
    }
}
