// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PartyHandle : RemoteTableHandle<EventContext, Party>
        {
            protected override string RemoteTableName => "party";

            public sealed class CodeUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Party row) => row.Code;

                public CodeUniqueIndex(PartyHandle table) : base(table) { }
            }

            public readonly CodeUniqueIndex Code;

            public sealed class HostIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Party row) => row.Host;

                public HostIndex(PartyHandle table) : base(table) { }
            }

            public readonly HostIndex Host;

            internal PartyHandle(DbConnection conn) : base(conn)
            {
                Code = new(this);
                Host = new(this);
            }

            protected override object GetPrimaryKey(Party row) => row.Code;
        }

        public readonly PartyHandle Party;
    }

    public sealed class PartyCols
    {
        public global::SpacetimeDB.Col<Party, string> Code { get; }
        public global::SpacetimeDB.Col<Party, SpacetimeDB.Identity> Host { get; }
        public global::SpacetimeDB.Col<Party, long> CreatedTick { get; }
        public global::SpacetimeDB.Col<Party, uint> MemberCount { get; }
        public global::SpacetimeDB.Col<Party, bool> IsOpen { get; }

        public PartyCols(string tableName)
        {
            Code = new global::SpacetimeDB.Col<Party, string>(tableName, "code");
            Host = new global::SpacetimeDB.Col<Party, SpacetimeDB.Identity>(tableName, "host");
            CreatedTick = new global::SpacetimeDB.Col<Party, long>(tableName, "created_tick");
            MemberCount = new global::SpacetimeDB.Col<Party, uint>(tableName, "member_count");
            IsOpen = new global::SpacetimeDB.Col<Party, bool>(tableName, "is_open");
        }
    }

    public sealed class PartyIxCols
    {
        public global::SpacetimeDB.IxCol<Party, string> Code { get; }
        public global::SpacetimeDB.IxCol<Party, SpacetimeDB.Identity> Host { get; }

        public PartyIxCols(string tableName)
        {
            Code = new global::SpacetimeDB.IxCol<Party, string>(tableName, "code");
            Host = new global::SpacetimeDB.IxCol<Party, SpacetimeDB.Identity>(tableName, "host");
        }
    }
}
