// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VillainLedgerHandle : RemoteTableHandle<EventContext, VillainLedger>
        {
            protected override string RemoteTableName => "villain_ledger";

            public sealed class ActUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(VillainLedger row) => row.Act;

                public ActUniqueIndex(VillainLedgerHandle table) : base(table) { }
            }

            public readonly ActUniqueIndex Act;

            internal VillainLedgerHandle(DbConnection conn) : base(conn)
            {
                Act = new(this);
            }

            protected override object GetPrimaryKey(VillainLedger row) => row.Act;
        }

        public readonly VillainLedgerHandle VillainLedger;
    }

    public sealed class VillainLedgerCols
    {
        public global::SpacetimeDB.Col<VillainLedger, uint> Act { get; }
        public global::SpacetimeDB.Col<VillainLedger, string> Kept { get; }
        public global::SpacetimeDB.Col<VillainLedger, string> Lost { get; }
        public global::SpacetimeDB.Col<VillainLedger, string> PlayersCarry { get; }
        public global::SpacetimeDB.Col<VillainLedger, string> ComposureTone { get; }

        public VillainLedgerCols(string tableName)
        {
            Act = new global::SpacetimeDB.Col<VillainLedger, uint>(tableName, "act");
            Kept = new global::SpacetimeDB.Col<VillainLedger, string>(tableName, "kept");
            Lost = new global::SpacetimeDB.Col<VillainLedger, string>(tableName, "lost");
            PlayersCarry = new global::SpacetimeDB.Col<VillainLedger, string>(tableName, "players_carry");
            ComposureTone = new global::SpacetimeDB.Col<VillainLedger, string>(tableName, "composure_tone");
        }
    }

    public sealed class VillainLedgerIxCols
    {
        public global::SpacetimeDB.IxCol<VillainLedger, uint> Act { get; }

        public VillainLedgerIxCols(string tableName)
        {
            Act = new global::SpacetimeDB.IxCol<VillainLedger, uint>(tableName, "act");
        }
    }
}
