// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Account
    {
        [DataMember(Name = "username_key")]
        public string UsernameKey;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "pin_hash")]
        public string PinHash;
        [DataMember(Name = "pin_salt")]
        public string PinSalt;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "failed_attempts")]
        public int FailedAttempts;
        [DataMember(Name = "lockout_until_tick")]
        public long LockoutUntilTick;
        [DataMember(Name = "created_tick")]
        public long CreatedTick;
        [DataMember(Name = "last_login_tick")]
        public long LastLoginTick;

        public Account(
            string UsernameKey,
            string DisplayName,
            string PinHash,
            string PinSalt,
            SpacetimeDB.Identity Identity,
            int FailedAttempts,
            long LockoutUntilTick,
            long CreatedTick,
            long LastLoginTick
        )
        {
            this.UsernameKey = UsernameKey;
            this.DisplayName = DisplayName;
            this.PinHash = PinHash;
            this.PinSalt = PinSalt;
            this.Identity = Identity;
            this.FailedAttempts = FailedAttempts;
            this.LockoutUntilTick = LockoutUntilTick;
            this.CreatedTick = CreatedTick;
            this.LastLoginTick = LastLoginTick;
        }

        public Account()
        {
            this.UsernameKey = "";
            this.DisplayName = "";
            this.PinHash = "";
            this.PinSalt = "";
        }
    }
}
