// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AccountDossier
    {
        [DataMember(Name = "username_key")]
        public string UsernameKey;
        [DataMember(Name = "nickname")]
        public string Nickname;
        [DataMember(Name = "dossier_text")]
        public string DossierText;
        [DataMember(Name = "grudge_score")]
        public int GrudgeScore;
        [DataMember(Name = "runs_seen")]
        public int RunsSeen;

        public AccountDossier(
            string UsernameKey,
            string Nickname,
            string DossierText,
            int GrudgeScore,
            int RunsSeen
        )
        {
            this.UsernameKey = UsernameKey;
            this.Nickname = Nickname;
            this.DossierText = DossierText;
            this.GrudgeScore = GrudgeScore;
            this.RunsSeen = RunsSeen;
        }

        public AccountDossier()
        {
            this.UsernameKey = "";
            this.Nickname = "";
            this.DossierText = "";
        }
    }
}
