// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActSecret
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "sister_location")]
        public string SisterLocation;
        [DataMember(Name = "billionaire_location")]
        public string BillionaireLocation;
        [DataMember(Name = "sister_clue_act")]
        public uint SisterClueAct;

        public ActSecret(
            uint Id,
            string SisterLocation,
            string BillionaireLocation,
            uint SisterClueAct
        )
        {
            this.Id = Id;
            this.SisterLocation = SisterLocation;
            this.BillionaireLocation = BillionaireLocation;
            this.SisterClueAct = SisterClueAct;
        }

        public ActSecret()
        {
            this.SisterLocation = "";
            this.BillionaireLocation = "";
        }
    }
}
