// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BillionaireRequest
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "asker")]
        public SpacetimeDB.Identity Asker;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "claimed_by")]
        public SpacetimeDB.Identity? ClaimedBy;
        [DataMember(Name = "context")]
        public string Context;
        [DataMember(Name = "target_identity")]
        public SpacetimeDB.Identity? TargetIdentity;
        [DataMember(Name = "created_tick")]
        public long CreatedTick;
        [DataMember(Name = "claimed_tick")]
        public long ClaimedTick;

        public BillionaireRequest(
            ulong Id,
            string Kind,
            SpacetimeDB.Identity Asker,
            string Status,
            SpacetimeDB.Identity? ClaimedBy,
            string Context,
            SpacetimeDB.Identity? TargetIdentity,
            long CreatedTick,
            long ClaimedTick
        )
        {
            this.Id = Id;
            this.Kind = Kind;
            this.Asker = Asker;
            this.Status = Status;
            this.ClaimedBy = ClaimedBy;
            this.Context = Context;
            this.TargetIdentity = TargetIdentity;
            this.CreatedTick = CreatedTick;
            this.ClaimedTick = ClaimedTick;
        }

        public BillionaireRequest()
        {
            this.Kind = "";
            this.Status = "";
            this.Context = "";
        }
    }
}
