// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Billionaire
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "dialogue")]
        public string Dialogue;
        [DataMember(Name = "animation_trigger")]
        public string AnimationTrigger;
        [DataMember(Name = "mood")]
        public string Mood;
        [DataMember(Name = "target_member")]
        public SpacetimeDB.Identity? TargetMember;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "seq")]
        public uint Seq;
        [DataMember(Name = "last_spoke_tick")]
        public long LastSpokeTick;
        [DataMember(Name = "busy_until_tick")]
        public long BusyUntilTick;
        [DataMember(Name = "busy_interaction_id")]
        public ulong BusyInteractionId;
        [DataMember(Name = "odds_episode_tick")]
        public long OddsEpisodeTick;
        [DataMember(Name = "launch_tick")]
        public long LaunchTick;
        [DataMember(Name = "run_id")]
        public ulong RunId;

        public Billionaire(
            uint Id,
            string DisplayName,
            string Dialogue,
            string AnimationTrigger,
            string Mood,
            SpacetimeDB.Identity? TargetMember,
            string Kind,
            uint Seq,
            long LastSpokeTick,
            long BusyUntilTick,
            ulong BusyInteractionId,
            long OddsEpisodeTick,
            long LaunchTick,
            ulong RunId
        )
        {
            this.Id = Id;
            this.DisplayName = DisplayName;
            this.Dialogue = Dialogue;
            this.AnimationTrigger = AnimationTrigger;
            this.Mood = Mood;
            this.TargetMember = TargetMember;
            this.Kind = Kind;
            this.Seq = Seq;
            this.LastSpokeTick = LastSpokeTick;
            this.BusyUntilTick = BusyUntilTick;
            this.BusyInteractionId = BusyInteractionId;
            this.OddsEpisodeTick = OddsEpisodeTick;
            this.LaunchTick = LaunchTick;
            this.RunId = RunId;
        }

        public Billionaire()
        {
            this.DisplayName = "";
            this.Dialogue = "";
            this.AnimationTrigger = "";
            this.Mood = "";
            this.Kind = "";
        }
    }
}
