// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClueCombo
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "required_clue_ids")]
        public System.Collections.Generic.List<ulong> RequiredClueIds;
        [DataMember(Name = "yields_clue_id")]
        public ulong YieldsClueId;
        [DataMember(Name = "is_act_goal")]
        public bool IsActGoal;
        [DataMember(Name = "act")]
        public uint Act;

        public ClueCombo(
            ulong Id,
            System.Collections.Generic.List<ulong> RequiredClueIds,
            ulong YieldsClueId,
            bool IsActGoal,
            uint Act
        )
        {
            this.Id = Id;
            this.RequiredClueIds = RequiredClueIds;
            this.YieldsClueId = YieldsClueId;
            this.IsActGoal = IsActGoal;
            this.Act = Act;
        }

        public ClueCombo()
        {
            this.RequiredClueIds = new();
        }
    }
}
