// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClueReveal
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "run_id")]
        public ulong RunId;
        [DataMember(Name = "clue_code")]
        public string ClueCode;
        [DataMember(Name = "fact_text")]
        public string FactText;
        [DataMember(Name = "act")]
        public uint Act;

        public ClueReveal(
            ulong Id,
            ulong RunId,
            string ClueCode,
            string FactText,
            uint Act
        )
        {
            this.Id = Id;
            this.RunId = RunId;
            this.ClueCode = ClueCode;
            this.FactText = FactText;
            this.Act = Act;
        }

        public ClueReveal()
        {
            this.ClueCode = "";
            this.FactText = "";
        }
    }
}
