// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Clue
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "fact_text")]
        public string FactText;
        [DataMember(Name = "truth")]
        public string Truth;
        [DataMember(Name = "overridden_by_clue_id")]
        public ulong OverriddenByClueId;
        [DataMember(Name = "act")]
        public uint Act;
        [DataMember(Name = "points_to")]
        public string PointsTo;

        public Clue(
            ulong Id,
            string Code,
            string FactText,
            string Truth,
            ulong OverriddenByClueId,
            uint Act,
            string PointsTo
        )
        {
            this.Id = Id;
            this.Code = Code;
            this.FactText = FactText;
            this.Truth = Truth;
            this.OverriddenByClueId = OverriddenByClueId;
            this.Act = Act;
            this.PointsTo = PointsTo;
        }

        public Clue()
        {
            this.Code = "";
            this.FactText = "";
            this.Truth = "";
            this.PointsTo = "";
        }
    }
}
