// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FavorDelta
    {
        [DataMember(Name = "member")]
        public SpacetimeDB.Identity Member;
        [DataMember(Name = "delta")]
        public int Delta;

        public FavorDelta(
            SpacetimeDB.Identity Member,
            int Delta
        )
        {
            this.Member = Member;
            this.Delta = Delta;
        }

        public FavorDelta()
        {
        }
    }
}
