// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HookSpec
    {
        [DataMember(Name = "subject")]
        public string Subject;
        [DataMember(Name = "assertion")]
        public string Assertion;
        [DataMember(Name = "is_lie")]
        public bool IsLie;
        [DataMember(Name = "real_truth")]
        public string RealTruth;

        public HookSpec(
            string Subject,
            string Assertion,
            bool IsLie,
            string RealTruth
        )
        {
            this.Subject = Subject;
            this.Assertion = Assertion;
            this.IsLie = IsLie;
            this.RealTruth = RealTruth;
        }

        public HookSpec()
        {
            this.Subject = "";
            this.Assertion = "";
            this.RealTruth = "";
        }
    }
}
