// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LobbyHook
    {
        [DataMember(Name = "hook_id")]
        public ulong HookId;
        [DataMember(Name = "run_id")]
        public ulong RunId;
        [DataMember(Name = "subject")]
        public string Subject;
        [DataMember(Name = "assertion")]
        public string Assertion;
        [DataMember(Name = "seq")]
        public uint Seq;

        public LobbyHook(
            ulong HookId,
            ulong RunId,
            string Subject,
            string Assertion,
            uint Seq
        )
        {
            this.HookId = HookId;
            this.RunId = RunId;
            this.Subject = Subject;
            this.Assertion = Assertion;
            this.Seq = Seq;
        }

        public LobbyHook()
        {
            this.Subject = "";
            this.Assertion = "";
        }
    }
}
