// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LobbyMember
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "nickname")]
        public string Nickname;
        [DataMember(Name = "character_id")]
        public uint CharacterId;
        [DataMember(Name = "is_ready")]
        public bool IsReady;
        [DataMember(Name = "ready_tick")]
        public long ReadyTick;
        [DataMember(Name = "last_activity_tick")]
        public long LastActivityTick;
        [DataMember(Name = "swap_count")]
        public uint SwapCount;
        [DataMember(Name = "slot")]
        public uint Slot;
        [DataMember(Name = "seq")]
        public uint Seq;
        [DataMember(Name = "survival_pct")]
        public int SurvivalPct;
        [DataMember(Name = "death_prediction")]
        public string DeathPrediction;
        [DataMember(Name = "callback_tag")]
        public string CallbackTag;
        [DataMember(Name = "allegiance")]
        public string Allegiance;
        [DataMember(Name = "favor")]
        public int Favor;
        [DataMember(Name = "is_expedition_lead")]
        public bool IsExpeditionLead;
        [DataMember(Name = "is_liability")]
        public bool IsLiability;
        [DataMember(Name = "whisper_text")]
        public string WhisperText;
        [DataMember(Name = "whisper_about")]
        public SpacetimeDB.Identity? WhisperAbout;
        [DataMember(Name = "whisper_seq")]
        public uint WhisperSeq;
        [DataMember(Name = "party_id")]
        public string PartyId;

        public LobbyMember(
            SpacetimeDB.Identity Identity,
            string Username,
            string Nickname,
            uint CharacterId,
            bool IsReady,
            long ReadyTick,
            long LastActivityTick,
            uint SwapCount,
            uint Slot,
            uint Seq,
            int SurvivalPct,
            string DeathPrediction,
            string CallbackTag,
            string Allegiance,
            int Favor,
            bool IsExpeditionLead,
            bool IsLiability,
            string WhisperText,
            SpacetimeDB.Identity? WhisperAbout,
            uint WhisperSeq,
            string PartyId
        )
        {
            this.Identity = Identity;
            this.Username = Username;
            this.Nickname = Nickname;
            this.CharacterId = CharacterId;
            this.IsReady = IsReady;
            this.ReadyTick = ReadyTick;
            this.LastActivityTick = LastActivityTick;
            this.SwapCount = SwapCount;
            this.Slot = Slot;
            this.Seq = Seq;
            this.SurvivalPct = SurvivalPct;
            this.DeathPrediction = DeathPrediction;
            this.CallbackTag = CallbackTag;
            this.Allegiance = Allegiance;
            this.Favor = Favor;
            this.IsExpeditionLead = IsExpeditionLead;
            this.IsLiability = IsLiability;
            this.WhisperText = WhisperText;
            this.WhisperAbout = WhisperAbout;
            this.WhisperSeq = WhisperSeq;
            this.PartyId = PartyId;
        }

        public LobbyMember()
        {
            this.Username = "";
            this.Nickname = "";
            this.DeathPrediction = "";
            this.CallbackTag = "";
            this.Allegiance = "";
            this.WhisperText = "";
            this.PartyId = "";
        }
    }
}
