// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LoggedOutPlayerData
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "character_class")]
        public string CharacterClass;
        [DataMember(Name = "color")]
        public string Color;
        [DataMember(Name = "last_seen")]
        public SpacetimeDB.Timestamp LastSeen;

        public LoggedOutPlayerData(
            SpacetimeDB.Identity Identity,
            string Username,
            string CharacterClass,
            string Color,
            SpacetimeDB.Timestamp LastSeen
        )
        {
            this.Identity = Identity;
            this.Username = Username;
            this.CharacterClass = CharacterClass;
            this.Color = Color;
            this.LastSeen = LastSeen;
        }

        public LoggedOutPlayerData()
        {
            this.Username = "";
            this.CharacterClass = "";
            this.Color = "";
        }
    }
}
