// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Npc
    {
        [DataMember(Name = "npc_id")]
        public ulong NpcId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "archetype")]
        public string Archetype;
        [DataMember(Name = "position")]
        public Vector3 Position;
        [DataMember(Name = "dialogue")]
        public string Dialogue;
        [DataMember(Name = "animation_trigger")]
        public string AnimationTrigger;
        [DataMember(Name = "game_action")]
        public string GameAction;
        [DataMember(Name = "target_player")]
        public SpacetimeDB.Identity? TargetPlayer;
        [DataMember(Name = "trust")]
        public int Trust;
        [DataMember(Name = "sanity")]
        public int Sanity;
        [DataMember(Name = "seq")]
        public uint Seq;
        [DataMember(Name = "last_spoke_tick")]
        public long LastSpokeTick;
        [DataMember(Name = "busy_until_tick")]
        public long BusyUntilTick;
        [DataMember(Name = "busy_interaction_id")]
        public ulong BusyInteractionId;

        public Npc(
            ulong NpcId,
            string DisplayName,
            string Archetype,
            Vector3 Position,
            string Dialogue,
            string AnimationTrigger,
            string GameAction,
            SpacetimeDB.Identity? TargetPlayer,
            int Trust,
            int Sanity,
            uint Seq,
            long LastSpokeTick,
            long BusyUntilTick,
            ulong BusyInteractionId
        )
        {
            this.NpcId = NpcId;
            this.DisplayName = DisplayName;
            this.Archetype = Archetype;
            this.Position = Position;
            this.Dialogue = Dialogue;
            this.AnimationTrigger = AnimationTrigger;
            this.GameAction = GameAction;
            this.TargetPlayer = TargetPlayer;
            this.Trust = Trust;
            this.Sanity = Sanity;
            this.Seq = Seq;
            this.LastSpokeTick = LastSpokeTick;
            this.BusyUntilTick = BusyUntilTick;
            this.BusyInteractionId = BusyInteractionId;
        }

        public Npc()
        {
            this.DisplayName = "";
            this.Archetype = "";
            this.Position = new();
            this.Dialogue = "";
            this.AnimationTrigger = "";
            this.GameAction = "";
        }
    }
}
