// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcCognition
    {
        [DataMember(Name = "npc_id")]
        public ulong NpcId;
        [DataMember(Name = "persona")]
        public string Persona;
        [DataMember(Name = "memory")]
        public string Memory;
        [DataMember(Name = "last_raw_output")]
        public string LastRawOutput;

        public NpcCognition(
            ulong NpcId,
            string Persona,
            string Memory,
            string LastRawOutput
        )
        {
            this.NpcId = NpcId;
            this.Persona = Persona;
            this.Memory = Memory;
            this.LastRawOutput = LastRawOutput;
        }

        public NpcCognition()
        {
            this.Persona = "";
            this.Memory = "";
            this.LastRawOutput = "";
        }
    }
}
