// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcInteraction
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_id")]
        public ulong NpcId;
        [DataMember(Name = "asker")]
        public SpacetimeDB.Identity Asker;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "claimed_by")]
        public SpacetimeDB.Identity? ClaimedBy;
        [DataMember(Name = "player_distance")]
        public float PlayerDistance;
        [DataMember(Name = "is_player_armed")]
        public bool IsPlayerArmed;
        [DataMember(Name = "flashlight_in_face")]
        public bool FlashlightInFace;
        [DataMember(Name = "transcript")]
        public string Transcript;
        [DataMember(Name = "trust_at_ask")]
        public int TrustAtAsk;
        [DataMember(Name = "sanity_at_ask")]
        public int SanityAtAsk;
        [DataMember(Name = "created_tick")]
        public long CreatedTick;
        [DataMember(Name = "claimed_tick")]
        public long ClaimedTick;

        public NpcInteraction(
            ulong Id,
            ulong NpcId,
            SpacetimeDB.Identity Asker,
            string Status,
            SpacetimeDB.Identity? ClaimedBy,
            float PlayerDistance,
            bool IsPlayerArmed,
            bool FlashlightInFace,
            string Transcript,
            int TrustAtAsk,
            int SanityAtAsk,
            long CreatedTick,
            long ClaimedTick
        )
        {
            this.Id = Id;
            this.NpcId = NpcId;
            this.Asker = Asker;
            this.Status = Status;
            this.ClaimedBy = ClaimedBy;
            this.PlayerDistance = PlayerDistance;
            this.IsPlayerArmed = IsPlayerArmed;
            this.FlashlightInFace = FlashlightInFace;
            this.Transcript = Transcript;
            this.TrustAtAsk = TrustAtAsk;
            this.SanityAtAsk = SanityAtAsk;
            this.CreatedTick = CreatedTick;
            this.ClaimedTick = ClaimedTick;
        }

        public NpcInteraction()
        {
            this.Status = "";
            this.Transcript = "";
        }
    }
}
