// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcKnowledge
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_id")]
        public ulong NpcId;
        [DataMember(Name = "clue_id")]
        public ulong ClueId;
        [DataMember(Name = "min_trust")]
        public float MinTrust;
        [DataMember(Name = "max_fear")]
        public float MaxFear;
        [DataMember(Name = "required_flag")]
        public string RequiredFlag;
        [DataMember(Name = "reveal_if_surrendered")]
        public bool RevealIfSurrendered;

        public NpcKnowledge(
            ulong Id,
            ulong NpcId,
            ulong ClueId,
            float MinTrust,
            float MaxFear,
            string RequiredFlag,
            bool RevealIfSurrendered
        )
        {
            this.Id = Id;
            this.NpcId = NpcId;
            this.ClueId = ClueId;
            this.MinTrust = MinTrust;
            this.MaxFear = MaxFear;
            this.RequiredFlag = RequiredFlag;
            this.RevealIfSurrendered = RevealIfSurrendered;
        }

        public NpcKnowledge()
        {
            this.RequiredFlag = "";
        }
    }
}
