// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcPlayerState
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "npc_id")]
        public ulong NpcId;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "trust")]
        public float Trust;
        [DataMember(Name = "fear")]
        public float Fear;
        [DataMember(Name = "flags")]
        public string Flags;
        [DataMember(Name = "memory_note")]
        public string MemoryNote;
        [DataMember(Name = "last_interaction")]
        public long LastInteraction;

        public NpcPlayerState(
            ulong Id,
            ulong NpcId,
            SpacetimeDB.Identity Player,
            float Trust,
            float Fear,
            string Flags,
            string MemoryNote,
            long LastInteraction
        )
        {
            this.Id = Id;
            this.NpcId = NpcId;
            this.Player = Player;
            this.Trust = Trust;
            this.Fear = Fear;
            this.Flags = Flags;
            this.MemoryNote = MemoryNote;
            this.LastInteraction = LastInteraction;
        }

        public NpcPlayerState()
        {
            this.Flags = "";
            this.MemoryNote = "";
        }
    }
}
