// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcUtterance
    {
        [DataMember(Name = "interaction_id")]
        public ulong InteractionId;
        [DataMember(Name = "transcript")]
        public string Transcript;

        public NpcUtterance(
            ulong InteractionId,
            string Transcript
        )
        {
            this.InteractionId = InteractionId;
            this.Transcript = Transcript;
        }

        public NpcUtterance()
        {
            this.Transcript = "";
        }
    }
}
