// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OddsUpdate
    {
        [DataMember(Name = "member")]
        public SpacetimeDB.Identity Member;
        [DataMember(Name = "survival_pct")]
        public int SurvivalPct;
        [DataMember(Name = "death_prediction")]
        public string DeathPrediction;
        [DataMember(Name = "callback_tag")]
        public string CallbackTag;

        public OddsUpdate(
            SpacetimeDB.Identity Member,
            int SurvivalPct,
            string DeathPrediction,
            string CallbackTag
        )
        {
            this.Member = Member;
            this.SurvivalPct = SurvivalPct;
            this.DeathPrediction = DeathPrediction;
            this.CallbackTag = CallbackTag;
        }

        public OddsUpdate()
        {
            this.DeathPrediction = "";
            this.CallbackTag = "";
        }
    }
}
