// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Party
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "host")]
        public SpacetimeDB.Identity Host;
        [DataMember(Name = "created_tick")]
        public long CreatedTick;
        [DataMember(Name = "member_count")]
        public uint MemberCount;
        [DataMember(Name = "is_open")]
        public bool IsOpen;

        public Party(
            string Code,
            SpacetimeDB.Identity Host,
            long CreatedTick,
            uint MemberCount,
            bool IsOpen
        )
        {
            this.Code = Code;
            this.Host = Host;
            this.CreatedTick = CreatedTick;
            this.MemberCount = MemberCount;
            this.IsOpen = IsOpen;
        }

        public Party()
        {
            this.Code = "";
        }
    }
}
