// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PartyClue
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "run_id")]
        public ulong RunId;
        [DataMember(Name = "clue_id")]
        public ulong ClueId;
        [DataMember(Name = "revealed_by_npc")]
        public ulong RevealedByNpc;
        [DataMember(Name = "revealed_to")]
        public SpacetimeDB.Identity RevealedTo;

        public PartyClue(
            ulong Id,
            ulong RunId,
            ulong ClueId,
            ulong RevealedByNpc,
            SpacetimeDB.Identity RevealedTo
        )
        {
            this.Id = Id;
            this.RunId = RunId;
            this.ClueId = ClueId;
            this.RevealedByNpc = RevealedByNpc;
            this.RevealedTo = RevealedTo;
        }

        public PartyClue()
        {
        }
    }
}
