// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VillainLedger
    {
        [DataMember(Name = "act")]
        public uint Act;
        [DataMember(Name = "kept")]
        public string Kept;
        [DataMember(Name = "lost")]
        public string Lost;
        [DataMember(Name = "players_carry")]
        public string PlayersCarry;
        [DataMember(Name = "composure_tone")]
        public string ComposureTone;

        public VillainLedger(
            uint Act,
            string Kept,
            string Lost,
            string PlayersCarry,
            string ComposureTone
        )
        {
            this.Act = Act;
            this.Kept = Kept;
            this.Lost = Lost;
            this.PlayersCarry = PlayersCarry;
            this.ComposureTone = ComposureTone;
        }

        public VillainLedger()
        {
            this.Kept = "";
            this.Lost = "";
            this.PlayersCarry = "";
            this.ComposureTone = "";
        }
    }
}
