// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldState
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "now_tick")]
        public long NowTick;
        [DataMember(Name = "time_of_day")]
        public string TimeOfDay;
        [DataMember(Name = "weather_conditions")]
        public string WeatherConditions;
        [DataMember(Name = "patron_dread")]
        public int PatronDread;
        [DataMember(Name = "current_act")]
        public uint CurrentAct;
        [DataMember(Name = "breach_progress")]
        public float BreachProgress;
        [DataMember(Name = "escape_cut_off")]
        public bool EscapeCutOff;
        [DataMember(Name = "act_goal_met")]
        public bool ActGoalMet;

        public WorldState(
            uint Id,
            long NowTick,
            string TimeOfDay,
            string WeatherConditions,
            int PatronDread,
            uint CurrentAct,
            float BreachProgress,
            bool EscapeCutOff,
            bool ActGoalMet
        )
        {
            this.Id = Id;
            this.NowTick = NowTick;
            this.TimeOfDay = TimeOfDay;
            this.WeatherConditions = WeatherConditions;
            this.PatronDread = PatronDread;
            this.CurrentAct = CurrentAct;
            this.BreachProgress = BreachProgress;
            this.EscapeCutOff = EscapeCutOff;
            this.ActGoalMet = ActGoalMet;
        }

        public WorldState()
        {
            this.TimeOfDay = "";
            this.WeatherConditions = "";
        }
    }
}
