// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BillionaireHandle : RemoteTableHandle<EventContext, Billionaire>
        {
            protected override string RemoteTableName => "billionaire";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Billionaire row) => row.Id;

                public IdUniqueIndex(BillionaireHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BillionaireHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Billionaire row) => row.Id;
        }

        public readonly BillionaireHandle Billionaire;
    }

    public sealed class BillionaireCols
    {
        public global::SpacetimeDB.Col<Billionaire, uint> Id { get; }
        public global::SpacetimeDB.Col<Billionaire, string> DisplayName { get; }
        public global::SpacetimeDB.Col<Billionaire, string> Dialogue { get; }
        public global::SpacetimeDB.Col<Billionaire, string> AnimationTrigger { get; }
        public global::SpacetimeDB.Col<Billionaire, string> Mood { get; }
        public global::SpacetimeDB.Col<Billionaire, SpacetimeDB.Identity> TargetMember { get; }
        public global::SpacetimeDB.Col<Billionaire, string> Kind { get; }
        public global::SpacetimeDB.Col<Billionaire, uint> Seq { get; }
        public global::SpacetimeDB.Col<Billionaire, long> LastSpokeTick { get; }
        public global::SpacetimeDB.Col<Billionaire, long> BusyUntilTick { get; }
        public global::SpacetimeDB.Col<Billionaire, ulong> BusyInteractionId { get; }
        public global::SpacetimeDB.Col<Billionaire, long> OddsEpisodeTick { get; }
        public global::SpacetimeDB.Col<Billionaire, long> LaunchTick { get; }
        public global::SpacetimeDB.Col<Billionaire, ulong> RunId { get; }

        public BillionaireCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Billionaire, uint>(tableName, "id");
            DisplayName = new global::SpacetimeDB.Col<Billionaire, string>(tableName, "display_name");
            Dialogue = new global::SpacetimeDB.Col<Billionaire, string>(tableName, "dialogue");
            AnimationTrigger = new global::SpacetimeDB.Col<Billionaire, string>(tableName, "animation_trigger");
            Mood = new global::SpacetimeDB.Col<Billionaire, string>(tableName, "mood");
            TargetMember = new global::SpacetimeDB.Col<Billionaire, SpacetimeDB.Identity>(tableName, "target_member");
            Kind = new global::SpacetimeDB.Col<Billionaire, string>(tableName, "kind");
            Seq = new global::SpacetimeDB.Col<Billionaire, uint>(tableName, "seq");
            LastSpokeTick = new global::SpacetimeDB.Col<Billionaire, long>(tableName, "last_spoke_tick");
            BusyUntilTick = new global::SpacetimeDB.Col<Billionaire, long>(tableName, "busy_until_tick");
            BusyInteractionId = new global::SpacetimeDB.Col<Billionaire, ulong>(tableName, "busy_interaction_id");
            OddsEpisodeTick = new global::SpacetimeDB.Col<Billionaire, long>(tableName, "odds_episode_tick");
            LaunchTick = new global::SpacetimeDB.Col<Billionaire, long>(tableName, "launch_tick");
            RunId = new global::SpacetimeDB.Col<Billionaire, ulong>(tableName, "run_id");
        }
    }

    public sealed class BillionaireIxCols
    {
        public global::SpacetimeDB.IxCol<Billionaire, uint> Id { get; }

        public BillionaireIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Billionaire, uint>(tableName, "id");
        }
    }
}
