// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BillionaireRequestHandle : RemoteTableHandle<EventContext, BillionaireRequest>
        {
            protected override string RemoteTableName => "billionaire_request";

            public sealed class AskerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(BillionaireRequest row) => row.Asker;

                public AskerIndex(BillionaireRequestHandle table) : base(table) { }
            }

            public readonly AskerIndex Asker;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BillionaireRequest row) => row.Id;

                public IdUniqueIndex(BillionaireRequestHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class KindIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(BillionaireRequest row) => row.Kind;

                public KindIndex(BillionaireRequestHandle table) : base(table) { }
            }

            public readonly KindIndex Kind;

            public sealed class StatusIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(BillionaireRequest row) => row.Status;

                public StatusIndex(BillionaireRequestHandle table) : base(table) { }
            }

            public readonly StatusIndex Status;

            internal BillionaireRequestHandle(DbConnection conn) : base(conn)
            {
                Asker = new(this);
                Id = new(this);
                Kind = new(this);
                Status = new(this);
            }

            protected override object GetPrimaryKey(BillionaireRequest row) => row.Id;
        }

        public readonly BillionaireRequestHandle BillionaireRequest;
    }

    public sealed class BillionaireRequestCols
    {
        public global::SpacetimeDB.Col<BillionaireRequest, ulong> Id { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, string> Kind { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, SpacetimeDB.Identity> Asker { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, string> Status { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, SpacetimeDB.Identity> ClaimedBy { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, string> Context { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, SpacetimeDB.Identity> TargetIdentity { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, long> CreatedTick { get; }
        public global::SpacetimeDB.Col<BillionaireRequest, long> ClaimedTick { get; }

        public BillionaireRequestCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BillionaireRequest, ulong>(tableName, "id");
            Kind = new global::SpacetimeDB.Col<BillionaireRequest, string>(tableName, "kind");
            Asker = new global::SpacetimeDB.Col<BillionaireRequest, SpacetimeDB.Identity>(tableName, "asker");
            Status = new global::SpacetimeDB.Col<BillionaireRequest, string>(tableName, "status");
            ClaimedBy = new global::SpacetimeDB.Col<BillionaireRequest, SpacetimeDB.Identity>(tableName, "claimed_by");
            Context = new global::SpacetimeDB.Col<BillionaireRequest, string>(tableName, "context");
            TargetIdentity = new global::SpacetimeDB.Col<BillionaireRequest, SpacetimeDB.Identity>(tableName, "target_identity");
            CreatedTick = new global::SpacetimeDB.Col<BillionaireRequest, long>(tableName, "created_tick");
            ClaimedTick = new global::SpacetimeDB.Col<BillionaireRequest, long>(tableName, "claimed_tick");
        }
    }

    public sealed class BillionaireRequestIxCols
    {
        public global::SpacetimeDB.IxCol<BillionaireRequest, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<BillionaireRequest, string> Kind { get; }
        public global::SpacetimeDB.IxCol<BillionaireRequest, SpacetimeDB.Identity> Asker { get; }
        public global::SpacetimeDB.IxCol<BillionaireRequest, string> Status { get; }

        public BillionaireRequestIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BillionaireRequest, ulong>(tableName, "id");
            Kind = new global::SpacetimeDB.IxCol<BillionaireRequest, string>(tableName, "kind");
            Asker = new global::SpacetimeDB.IxCol<BillionaireRequest, SpacetimeDB.Identity>(tableName, "asker");
            Status = new global::SpacetimeDB.IxCol<BillionaireRequest, string>(tableName, "status");
        }
    }
}
