// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ForestEventHandle : RemoteTableHandle<EventContext, ForestEvent>
        {
            protected override string RemoteTableName => "forest_event";

            public sealed class EventIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ForestEvent row) => row.EventId;

                public EventIdUniqueIndex(ForestEventHandle table) : base(table) { }
            }

            public readonly EventIdUniqueIndex EventId;

            public sealed class KindIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(ForestEvent row) => row.Kind;

                public KindIndex(ForestEventHandle table) : base(table) { }
            }

            public readonly KindIndex Kind;

            public sealed class PlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ForestEvent row) => row.PlayerIdentity;

                public PlayerIdentityIndex(ForestEventHandle table) : base(table) { }
            }

            public readonly PlayerIdentityIndex PlayerIdentity;

            public sealed class RunIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ForestEvent row) => row.RunId;

                public RunIdIndex(ForestEventHandle table) : base(table) { }
            }

            public readonly RunIdIndex RunId;

            internal ForestEventHandle(DbConnection conn) : base(conn)
            {
                EventId = new(this);
                Kind = new(this);
                PlayerIdentity = new(this);
                RunId = new(this);
            }

            protected override object GetPrimaryKey(ForestEvent row) => row.EventId;
        }

        public readonly ForestEventHandle ForestEvent;
    }

    public sealed class ForestEventCols
    {
        public global::SpacetimeDB.Col<ForestEvent, ulong> EventId { get; }
        public global::SpacetimeDB.Col<ForestEvent, SpacetimeDB.Identity> PlayerIdentity { get; }
        public global::SpacetimeDB.Col<ForestEvent, string> Kind { get; }
        public global::SpacetimeDB.Col<ForestEvent, ulong> RunId { get; }
        public global::SpacetimeDB.Col<ForestEvent, string> Detail { get; }
        public global::SpacetimeDB.Col<ForestEvent, long> CreatedTick { get; }

        public ForestEventCols(string tableName)
        {
            EventId = new global::SpacetimeDB.Col<ForestEvent, ulong>(tableName, "event_id");
            PlayerIdentity = new global::SpacetimeDB.Col<ForestEvent, SpacetimeDB.Identity>(tableName, "player_identity");
            Kind = new global::SpacetimeDB.Col<ForestEvent, string>(tableName, "kind");
            RunId = new global::SpacetimeDB.Col<ForestEvent, ulong>(tableName, "run_id");
            Detail = new global::SpacetimeDB.Col<ForestEvent, string>(tableName, "detail");
            CreatedTick = new global::SpacetimeDB.Col<ForestEvent, long>(tableName, "created_tick");
        }
    }

    public sealed class ForestEventIxCols
    {
        public global::SpacetimeDB.IxCol<ForestEvent, ulong> EventId { get; }
        public global::SpacetimeDB.IxCol<ForestEvent, SpacetimeDB.Identity> PlayerIdentity { get; }
        public global::SpacetimeDB.IxCol<ForestEvent, string> Kind { get; }
        public global::SpacetimeDB.IxCol<ForestEvent, ulong> RunId { get; }

        public ForestEventIxCols(string tableName)
        {
            EventId = new global::SpacetimeDB.IxCol<ForestEvent, ulong>(tableName, "event_id");
            PlayerIdentity = new global::SpacetimeDB.IxCol<ForestEvent, SpacetimeDB.Identity>(tableName, "player_identity");
            Kind = new global::SpacetimeDB.IxCol<ForestEvent, string>(tableName, "kind");
            RunId = new global::SpacetimeDB.IxCol<ForestEvent, ulong>(tableName, "run_id");
        }
    }
}
