// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LobbyHookHandle : RemoteTableHandle<EventContext, LobbyHook>
        {
            protected override string RemoteTableName => "lobby_hook";

            public sealed class HookIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LobbyHook row) => row.HookId;

                public HookIdUniqueIndex(LobbyHookHandle table) : base(table) { }
            }

            public readonly HookIdUniqueIndex HookId;

            public sealed class RunIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(LobbyHook row) => row.RunId;

                public RunIdIndex(LobbyHookHandle table) : base(table) { }
            }

            public readonly RunIdIndex RunId;

            internal LobbyHookHandle(DbConnection conn) : base(conn)
            {
                HookId = new(this);
                RunId = new(this);
            }

            protected override object GetPrimaryKey(LobbyHook row) => row.HookId;
        }

        public readonly LobbyHookHandle LobbyHook;
    }

    public sealed class LobbyHookCols
    {
        public global::SpacetimeDB.Col<LobbyHook, ulong> HookId { get; }
        public global::SpacetimeDB.Col<LobbyHook, ulong> RunId { get; }
        public global::SpacetimeDB.Col<LobbyHook, string> Subject { get; }
        public global::SpacetimeDB.Col<LobbyHook, string> Assertion { get; }
        public global::SpacetimeDB.Col<LobbyHook, uint> Seq { get; }

        public LobbyHookCols(string tableName)
        {
            HookId = new global::SpacetimeDB.Col<LobbyHook, ulong>(tableName, "hook_id");
            RunId = new global::SpacetimeDB.Col<LobbyHook, ulong>(tableName, "run_id");
            Subject = new global::SpacetimeDB.Col<LobbyHook, string>(tableName, "subject");
            Assertion = new global::SpacetimeDB.Col<LobbyHook, string>(tableName, "assertion");
            Seq = new global::SpacetimeDB.Col<LobbyHook, uint>(tableName, "seq");
        }
    }

    public sealed class LobbyHookIxCols
    {
        public global::SpacetimeDB.IxCol<LobbyHook, ulong> HookId { get; }
        public global::SpacetimeDB.IxCol<LobbyHook, ulong> RunId { get; }

        public LobbyHookIxCols(string tableName)
        {
            HookId = new global::SpacetimeDB.IxCol<LobbyHook, ulong>(tableName, "hook_id");
            RunId = new global::SpacetimeDB.IxCol<LobbyHook, ulong>(tableName, "run_id");
        }
    }
}
