// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcInteractionHandle : RemoteTableHandle<EventContext, NpcInteraction>
        {
            protected override string RemoteTableName => "npc_interaction";

            public sealed class AskerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(NpcInteraction row) => row.Asker;

                public AskerIndex(NpcInteractionHandle table) : base(table) { }
            }

            public readonly AskerIndex Asker;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcInteraction row) => row.Id;

                public IdUniqueIndex(NpcInteractionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NpcIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(NpcInteraction row) => row.NpcId;

                public NpcIdIndex(NpcInteractionHandle table) : base(table) { }
            }

            public readonly NpcIdIndex NpcId;

            public sealed class StatusIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(NpcInteraction row) => row.Status;

                public StatusIndex(NpcInteractionHandle table) : base(table) { }
            }

            public readonly StatusIndex Status;

            internal NpcInteractionHandle(DbConnection conn) : base(conn)
            {
                Asker = new(this);
                Id = new(this);
                NpcId = new(this);
                Status = new(this);
            }

            protected override object GetPrimaryKey(NpcInteraction row) => row.Id;
        }

        public readonly NpcInteractionHandle NpcInteraction;
    }

    public sealed class NpcInteractionCols
    {
        public global::SpacetimeDB.Col<NpcInteraction, ulong> Id { get; }
        public global::SpacetimeDB.Col<NpcInteraction, ulong> NpcId { get; }
        public global::SpacetimeDB.Col<NpcInteraction, SpacetimeDB.Identity> Asker { get; }
        public global::SpacetimeDB.Col<NpcInteraction, string> Status { get; }
        public global::SpacetimeDB.Col<NpcInteraction, SpacetimeDB.Identity> ClaimedBy { get; }
        public global::SpacetimeDB.Col<NpcInteraction, float> PlayerDistance { get; }
        public global::SpacetimeDB.Col<NpcInteraction, bool> IsPlayerArmed { get; }
        public global::SpacetimeDB.Col<NpcInteraction, bool> FlashlightInFace { get; }
        public global::SpacetimeDB.Col<NpcInteraction, string> Transcript { get; }
        public global::SpacetimeDB.Col<NpcInteraction, int> TrustAtAsk { get; }
        public global::SpacetimeDB.Col<NpcInteraction, int> SanityAtAsk { get; }
        public global::SpacetimeDB.Col<NpcInteraction, long> CreatedTick { get; }
        public global::SpacetimeDB.Col<NpcInteraction, long> ClaimedTick { get; }

        public NpcInteractionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<NpcInteraction, ulong>(tableName, "id");
            NpcId = new global::SpacetimeDB.Col<NpcInteraction, ulong>(tableName, "npc_id");
            Asker = new global::SpacetimeDB.Col<NpcInteraction, SpacetimeDB.Identity>(tableName, "asker");
            Status = new global::SpacetimeDB.Col<NpcInteraction, string>(tableName, "status");
            ClaimedBy = new global::SpacetimeDB.Col<NpcInteraction, SpacetimeDB.Identity>(tableName, "claimed_by");
            PlayerDistance = new global::SpacetimeDB.Col<NpcInteraction, float>(tableName, "player_distance");
            IsPlayerArmed = new global::SpacetimeDB.Col<NpcInteraction, bool>(tableName, "is_player_armed");
            FlashlightInFace = new global::SpacetimeDB.Col<NpcInteraction, bool>(tableName, "flashlight_in_face");
            Transcript = new global::SpacetimeDB.Col<NpcInteraction, string>(tableName, "transcript");
            TrustAtAsk = new global::SpacetimeDB.Col<NpcInteraction, int>(tableName, "trust_at_ask");
            SanityAtAsk = new global::SpacetimeDB.Col<NpcInteraction, int>(tableName, "sanity_at_ask");
            CreatedTick = new global::SpacetimeDB.Col<NpcInteraction, long>(tableName, "created_tick");
            ClaimedTick = new global::SpacetimeDB.Col<NpcInteraction, long>(tableName, "claimed_tick");
        }
    }

    public sealed class NpcInteractionIxCols
    {
        public global::SpacetimeDB.IxCol<NpcInteraction, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<NpcInteraction, ulong> NpcId { get; }
        public global::SpacetimeDB.IxCol<NpcInteraction, SpacetimeDB.Identity> Asker { get; }
        public global::SpacetimeDB.IxCol<NpcInteraction, string> Status { get; }

        public NpcInteractionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<NpcInteraction, ulong>(tableName, "id");
            NpcId = new global::SpacetimeDB.IxCol<NpcInteraction, ulong>(tableName, "npc_id");
            Asker = new global::SpacetimeDB.IxCol<NpcInteraction, SpacetimeDB.Identity>(tableName, "asker");
            Status = new global::SpacetimeDB.IxCol<NpcInteraction, string>(tableName, "status");
        }
    }
}
