// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PartyChatHandle : RemoteTableHandle<EventContext, PartyChat>
        {
            protected override string RemoteTableName => "party_chat";

            public sealed class CreatedTickIndex : BTreeIndexBase<long>
            {
                protected override long GetKey(PartyChat row) => row.CreatedTick;

                public CreatedTickIndex(PartyChatHandle table) : base(table) { }
            }

            public readonly CreatedTickIndex CreatedTick;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PartyChat row) => row.Id;

                public IdUniqueIndex(PartyChatHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PartyIdIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(PartyChat row) => row.PartyId;

                public PartyIdIndex(PartyChatHandle table) : base(table) { }
            }

            public readonly PartyIdIndex PartyId;

            public sealed class SenderIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PartyChat row) => row.Sender;

                public SenderIndex(PartyChatHandle table) : base(table) { }
            }

            public readonly SenderIndex Sender;

            internal PartyChatHandle(DbConnection conn) : base(conn)
            {
                CreatedTick = new(this);
                Id = new(this);
                PartyId = new(this);
                Sender = new(this);
            }

            protected override object GetPrimaryKey(PartyChat row) => row.Id;
        }

        public readonly PartyChatHandle PartyChat;
    }

    public sealed class PartyChatCols
    {
        public global::SpacetimeDB.Col<PartyChat, ulong> Id { get; }
        public global::SpacetimeDB.Col<PartyChat, SpacetimeDB.Identity> Sender { get; }
        public global::SpacetimeDB.Col<PartyChat, string> SenderName { get; }
        public global::SpacetimeDB.Col<PartyChat, string> Body { get; }
        public global::SpacetimeDB.Col<PartyChat, long> CreatedTick { get; }
        public global::SpacetimeDB.Col<PartyChat, bool> IsBillionaire { get; }
        public global::SpacetimeDB.Col<PartyChat, bool> AddressedBillionaire { get; }
        public global::SpacetimeDB.Col<PartyChat, string> PartyId { get; }

        public PartyChatCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PartyChat, ulong>(tableName, "id");
            Sender = new global::SpacetimeDB.Col<PartyChat, SpacetimeDB.Identity>(tableName, "sender");
            SenderName = new global::SpacetimeDB.Col<PartyChat, string>(tableName, "sender_name");
            Body = new global::SpacetimeDB.Col<PartyChat, string>(tableName, "body");
            CreatedTick = new global::SpacetimeDB.Col<PartyChat, long>(tableName, "created_tick");
            IsBillionaire = new global::SpacetimeDB.Col<PartyChat, bool>(tableName, "is_billionaire");
            AddressedBillionaire = new global::SpacetimeDB.Col<PartyChat, bool>(tableName, "addressed_billionaire");
            PartyId = new global::SpacetimeDB.Col<PartyChat, string>(tableName, "party_id");
        }
    }

    public sealed class PartyChatIxCols
    {
        public global::SpacetimeDB.IxCol<PartyChat, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PartyChat, SpacetimeDB.Identity> Sender { get; }
        public global::SpacetimeDB.IxCol<PartyChat, long> CreatedTick { get; }
        public global::SpacetimeDB.IxCol<PartyChat, string> PartyId { get; }

        public PartyChatIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PartyChat, ulong>(tableName, "id");
            Sender = new global::SpacetimeDB.IxCol<PartyChat, SpacetimeDB.Identity>(tableName, "sender");
            CreatedTick = new global::SpacetimeDB.IxCol<PartyChat, long>(tableName, "created_tick");
            PartyId = new global::SpacetimeDB.IxCol<PartyChat, string>(tableName, "party_id");
        }
    }
}
