// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, PlayerData>
        {
            protected override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerData row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(PlayerData row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<PlayerData, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<PlayerData, string> Username { get; }
        public global::SpacetimeDB.Col<PlayerData, string> CharacterClass { get; }
        public global::SpacetimeDB.Col<PlayerData, Vector3> Position { get; }
        public global::SpacetimeDB.Col<PlayerData, Vector3> Rotation { get; }
        public global::SpacetimeDB.Col<PlayerData, int> Health { get; }
        public global::SpacetimeDB.Col<PlayerData, int> MaxHealth { get; }
        public global::SpacetimeDB.Col<PlayerData, int> Mana { get; }
        public global::SpacetimeDB.Col<PlayerData, int> MaxMana { get; }
        public global::SpacetimeDB.Col<PlayerData, string> CurrentAnimation { get; }
        public global::SpacetimeDB.Col<PlayerData, bool> IsMoving { get; }
        public global::SpacetimeDB.Col<PlayerData, bool> IsRunning { get; }
        public global::SpacetimeDB.Col<PlayerData, bool> IsAttacking { get; }
        public global::SpacetimeDB.Col<PlayerData, bool> IsCasting { get; }
        public global::SpacetimeDB.Col<PlayerData, uint> LastInputSeq { get; }
        public global::SpacetimeDB.Col<PlayerData, InputState> Input { get; }
        public global::SpacetimeDB.Col<PlayerData, string> Color { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<PlayerData, SpacetimeDB.Identity>(tableName, "identity");
            Username = new global::SpacetimeDB.Col<PlayerData, string>(tableName, "username");
            CharacterClass = new global::SpacetimeDB.Col<PlayerData, string>(tableName, "character_class");
            Position = new global::SpacetimeDB.Col<PlayerData, Vector3>(tableName, "position");
            Rotation = new global::SpacetimeDB.Col<PlayerData, Vector3>(tableName, "rotation");
            Health = new global::SpacetimeDB.Col<PlayerData, int>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<PlayerData, int>(tableName, "max_health");
            Mana = new global::SpacetimeDB.Col<PlayerData, int>(tableName, "mana");
            MaxMana = new global::SpacetimeDB.Col<PlayerData, int>(tableName, "max_mana");
            CurrentAnimation = new global::SpacetimeDB.Col<PlayerData, string>(tableName, "current_animation");
            IsMoving = new global::SpacetimeDB.Col<PlayerData, bool>(tableName, "is_moving");
            IsRunning = new global::SpacetimeDB.Col<PlayerData, bool>(tableName, "is_running");
            IsAttacking = new global::SpacetimeDB.Col<PlayerData, bool>(tableName, "is_attacking");
            IsCasting = new global::SpacetimeDB.Col<PlayerData, bool>(tableName, "is_casting");
            LastInputSeq = new global::SpacetimeDB.Col<PlayerData, uint>(tableName, "last_input_seq");
            Input = new global::SpacetimeDB.Col<PlayerData, InputState>(tableName, "input");
            Color = new global::SpacetimeDB.Col<PlayerData, string>(tableName, "color");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerData, SpacetimeDB.Identity> Identity { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<PlayerData, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
